var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[e]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,e){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,d={next:function(){if(f<a.length){var b=f++;return{value:e(b,a[b]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,e,f,d){if(e){f=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var b=a[d];b in f||(f[b]={});f=f[b]}a=a[a.length-1];d=f[a];e=e(d);e!=d&&null!=e&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,f){return f})}},"es6","es3");
$jscomp.findInternal=function(a,e,f){a instanceof String&&(a=String(a));for(var d=a.length,b=0;b<d;b++){var h=a[b];if(e.call(f,h,b,a))return{i:b,v:h}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6-impl","es3");var appInfoService=angular.module("appInfoService",[]);
appInfoService.factory("appInfo",["$shttp","$localStorage","user","$rootScope","$location","app","$timeout","$uibModal",function(a,e,f,d,b,h,c,g){var l;return{confDashboard:function(a,d){a.dashboard||(a.dashboard={tasks:!0,notifications:!1,orders:!1,reports:!0,emails:!1,pbl:!1,like:!1});d||(d=function(){});g.open({templateUrl:"templates/sys/confdashboard.html",controller:["$scope","$uibModalInstance","parentScope",function(b,c,h){b.ok=function(){d();c.close()};b.cancel=function(){d();c.close()};b.appInfo=
a;b.$watch("appInfo",function(d){e.set("dashboard"+a._id,JSON.stringify(a.dashboard))},!0)}],size:"lg",resolve:{parentScope:function(){return{}}}})},asDesktop:function(){return"function"==typeof require?!0:!1},commands:function(b,c){var h=d.getCacheFactory(b,"SYSTEM");a.get(server_url+"/api/"+b+"/menu?access_token="+e.get("token"),{cache:h}).then(function(b){b=b.data;d.commands=b.menu;d.cmdmodules=cmdmodules=b.modules;d.commands.forEach(function(b){b.title=getLabel(d.labels,"TEN_CT"+b.name.toUpperCase(),
b.title,d.lang,a).text;b.input.forEach(function(c){c.path?c.header=getLabel(d.labels,"TEN_CT"+c.path.toUpperCase(),c.header,d.lang,a).text:c.items&&(c.header=getLabel(d.labels,"TEN_CT"+(b.name+c.name).toUpperCase(),c.header,d.lang,a).text,c.items.forEach(function(e){e.path?e.header=getLabel(d.labels,"TEN_CT"+e.path.toUpperCase(),e.header,d.lang,a).text:e.group&&(e.group=getLabel(d.labels,"TEN_CT"+(b.name+c.name+e.name).toUpperCase(),e.group,d.lang,a).text,e.items.forEach(function(b){b.header=getLabel(d.labels,
"TEN_CT"+b.path.toUpperCase(),b.header,d.lang,a).text}))}))})});c&&c(null,d.commands)},function(a){if(!a.data){var h=e.getObject(b+"_menu_"+d.user.email);if(h){d.commands=h.menu;d.cmdmodules=cmdmodules=h.modules;c&&c(null,d.commands);return}}c&&c(a.data)})},get:function(a,d){l?d(null,l):h.get(a,a).then(function(a){l=a.data;console.log("appinfo",l);d(null,l)},function(b){console.log("get appinfo",b,a);d(error.data)})},label:function(b,c){var h=d.getCacheFactory(null,"SYSTEM",null,!1),f={},g=d.labelinfoSYS;
g||(g=e.getObject("labelinfoSYS","{}"),d.labelinfoSYS=g);_.extend(f,g);var m;async.parallel({check:function(c){0==_.values(g).length||"SYS"===b.toUpperCase()?(m=server_url+"/labels/SYS",a.get(m,{cache:h}).then(function(a){g=a.data;"SYS"===b.toUpperCase()&&(d.labelinfoSYS=g);_.extend(f,g);c()},function(a){a.data&&console.log("Can't get label info",b,a.data,m);c()})):(d.labelinfoSYS=g,c())}},function(g,q){if("SYS"!==b.toUpperCase()){var k="labelinfo"+b.toUpperCase();(g=d[k])||(g=e.getObject(k,"{}"));
_.extend(f,g);m=server_url+"/labels/"+b;a.get(m,{cache:h}).then(function(a){a=a.data;_.extend(f,a);d[k]=a},function(a){a.data&&console.log("Can't get label info",b,a.data)})}c(f)})},info:function(c,g){!id_app&&(id_app=e.get("id_app"))&&(d.id_app=id_app);if(!id_app&&!_.contains(paths_not_require_id_app,c))return g&&g("b\u1ea1n ph\u1ea3i ch\u1ecdn m\u1ed9t c\u00f4ng ty"),b.url("/app"),!1;f.getInfo(function(b,c){if(b)return g&&g(b),!1;if(endpoint&&e.get("endpoint64")!==endpoint+c.email){var f=server_url+
"/api/register-endpoint?ep="+encodeURI(endpoint);a.get(f).then(function(a){e.set("endpoint64",endpoint+c.email);console.log("register endpoint successfyll")},function(a){console.log("can not register endpoint",f,a.data)})}!d.app_info&&id_app?h.get(id_app,id_app).then(function(a){a=a.data;if(c.email===a.user_created)c.appAdmin=!0;else{var b=_.find(a.participants,function(a){return a.email==c.email});c.appAdmin=b&&b.admin?!0:!1}d.app_info=a;e.setObject("currentuser",c);e.setObject("appinfo"+id_app,
a);g&&g(null,c,a)},function(a){if(!a.data){var b=e.getObject("appinfo"+id_app);if(b)return d.app_info=b,g&&g(null,c,b),!0}g&&g(a.data)}):(d.app_info&&(c.email===d.app_info.user_created?c.appAdmin=!0:(b=_.find(d.app_info.participants,function(a){return a.email==c.email}),c.appAdmin=b&&b.admin?!0:!1)),g&&g(null,c,d.app_info))});return!0}}}]);
appInfoService.factory("$localStorage",["$window","$cookies","$rootScope","$shttp",function(a,e,f,d){return{remove:function(b){a.localStorage?a.localStorage[b]="":e[b]=""},set:function(b,d){a.localStorage?a.localStorage[b]=d:e[b]=d},get:function(b){return a.localStorage?a.localStorage[b]:e[b]},setObject:function(b,d){a.localStorage&&(a.localStorage[b]=JSON.stringify(d))},getObject:function(b,d){d||(d=[]);var c;a.localStorage&&(c=a.localStorage[b]);c||(c=d);if(_.isObject(c)||_.isArray(c))return c;
try{return JSON.parse(c)}catch(g){return d}}}}]);
appInfoService.factory("$shttp",["$rootScope","$http","$q",function(a,e,f){return{post:function(a,b,f){return e.post(a,b,f)},put:function(a,b,f){return e.put(a,b,f)},delete:function(a,b){return e.delete(a,b)},get:function(d,b){var h=f.defer(),c;b&&b.cache&&(c=!0!==b.cache?b.cache:a.getCacheFactory(null,b.cacheName?b.cacheName:"SYSTEM"));_online?(b&&b.cache&&(delete b.cache,delete b.cacheName),e.get(d,b).then(function(a){h.resolve(a);c&&c.put(d,a.data,function(a){a&&console.error("cached",d,a)})},
function(a){a.data?h.reject(a):c?c.get(d,function(a,b){b?h.resolve({data:b}):h.reject({data:"Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7"})}):h.reject({data:"KH\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7"})})):c?c.get(d,function(a,b){b?h.resolve({data:b}):(console.log("Not found cache for ",d),h.reject({data:"Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7"}))}):h.reject({data:"KH\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7"});
return h.promise}}}]);
appInfoService.factory("nodeWebkit",["$rootScope","$timeout","$location",function(a,e,f){var d=function(b,d,c){if(!endpoint){_.isObject(c)||(_.isFunction(c)?c={onClick:c}:_.isString(c)?c={url:c}:c||(c={}));var e={body:b,icon:server_url+"/images/icon/256x256.png",vibrate:[200,100,200,100,200,100,200],data:c};d||(d=a.program_name);var h=function(){if(c.onClick)c.onClick();else c.url&&a.$apply(function(){f.url(c.url)});window.focus();r.close()};if("SYSTEM"===c.sender)a.toast(c.content||b,6E4,c.title,
c.onClick,"success");else try{var r=new Notification(d,e);r.onclick=h}catch(t){a.toast(b)}}};return{notification:function(a,e,c){Notification?"granted"!==Notification.permission?Notification.requestPermission(function(b){"granted"===b&&d(a,e,c)}):d(a,e,c):d(a,e,c)}}}]);
appInfoService.factory("socket",["$rootScope",function(a){var e=io.connect(server_url);return{on:function(f,d){e.on(f,function(){var b=arguments;a.$apply(function(){d.apply(e,b)})})},once:function(f,d){e.once(f,function(){var b=arguments;a.$apply(function(){d.apply(e,b)})})},emit:function(f,d,b){e.emit(f,d,function(){var d=arguments;a.$apply(function(){b&&b.apply(e,d)})})}}}]);
appInfoService.factory("excel",[function(){return{tableToExcel:function(a,e){a=$($(a).html());e=a.find("table");0===e.length&&(a=a.wrap("<table>").parent(),e=a.find("table"));e.attr("border",1);e.attr("cellspacing",0);e.attr("bordercolor","#222");e.find("img").attr("height",64).attr("width",64);a=a.html();a=new Blob(["<http><head><meta charset='utf-8'/></head><body>"+(a||"")+"</body></html>"],{type:"text/plain;charset=utf-8;"});saveAs(a,"Report.xls")}}}]);
appInfoService.factory("printFactory",["$http","$localStorage","$rootScope","$compile","options","$timeout","numberToWord","$uibModal","$q","templaterpt",function(a,e,f,d,b,h,c,g,l,r){var t=function(a,b,d){var c=$(a);d&&d.width&&("printView"!==c.attr("id")?c=$("<div id='printView' style='width: "+d.width+"mm; margin: 0px auto;'>"+a+"</div>"):c.css("width",d.width+"mm"));var e,f,h;a=c.find("*:contains('{{getValue(')").each(function(){0<$(this).children().length||(e=this.innerHTML,f="",e.split(")}}").forEach(function(a){(h=
a)&&0<=h.indexOf("{{getValue(")&&(a=h.split("{{getValue(")[1].split(","),3==a.length&&(f="<span get-value module="+a[0]+" field="+a[1]+" condition="+a[2]+"></span>",e=e.replace("{{getValue("+a.join(",")+")}}",f)))}),$(this).html(e))});a=c.find("[ng-repeat]");0===a.length&&(a=c.find("#details"),0<a.length?a.attr("ng-repeat","r in datasource.details"):(a=c.find("tr:contains('{{r.')"),0===a.length&&(a=c.find("tr:contains('{{::r.')")),1===a.length?a.attr("ng-repeat","r in datasource.details"):1<a.length&&
("TBODY"===a.parent()[0].nodeName?a.parent().attr("ng-repeat","r in datasource.details"):a.wrapAll("<tbody ng-repeat='r in datasource.details'>"))));if(b)for(var g in b)_.isArray(b[g])&&(a=c.find("tr:contains('{{"+g+".')"),0===a.length&&(a=c.find("tr:contains('{{::"+g+".')")),1===a.length?a.attr("ng-repeat",g+" in datasource."+g):1<a.length&&("TBODY"===a.parent()[0].nodeName?a.parent().attr("ng-repeat",g+" in datasource."+g):a.wrapAll("<tbody ng-repeat='"+g+" in datasource."+g+"'>")));return c},u=
function(b,e,g,k,n){k.values={};k.doc_so=c;var m=g||k.data||{};k.company=k.appInfo=f.app_info;n||(n={});k.title=e||n.ten_mau_in||f.function_title;n.liens&&0!==n.liens.length||(n.liens=[{line:0,ma_lien:1,ten_lien:"Li\u00ean 1"}]);var q=l.defer();m&&m._id?a.get(server_url_report+"/api/"+id_app+"/vsocai/"+m._id).then(function(a){m.dinh_khoan=a.data;q.resolve(a.data)},function(a){console.log(a.data);q.resolve([])}):q.resolve([]);q.promise.then(function(a){async.mapSeries(n.liens,function(a,c){k.datasource=
JSON.parse(JSON.stringify(m));k.datasource.lien=a;a=t(b,k.datasource,n);var g=d(a[0].outerHTML)(k);h(function(){f.printS(g[0].outerHTML,e);h(function(){c()},200)},500)},function(){})},function(a){f.alert(a)})},p=function(a,b,c,d){a?(a=a.split("<em>").join("").split("</em>").join(""),b.printRpt=function(b,d){u(a,b,d,f,c)}):d&&(b.printRpt=function(a,c){v(d,a,c,b)})},v=function(a,b,c,d){f.user&&g.open({templateUrl:"templates/sys/chooseTemplate.html",controller:["$scope","$uibModalInstance","parentScope",
function(b,d,e){b.template;b.code=a.toUpperCase();b.ok=function(){d.close();if(b.template){var a=b.template.html_code;a&&(a=a.split("<em>").join("").split("</em>").join(""),u(a,b.titlePrint,c,f,b.template.exfields))}};b.cancel=function(){d.close()}}],size:"sm",resolve:{parentScope:function(){return d}}})};return{loadTemplate:function(a,c){f.user&&(e.getObject(id_app+"_"+f.user.email+"_"+a+"_option",{system:{}}),b.load(id_app,{filter:{id_func:a}}).then(function(b){b=b.data;1==b.length?(b=b[0],b.option&&
b.option.system&&b.option.defaultRpt?r.get(id_app,b.option.defaultRpt).then(function(b){b.data?p(b.data.html_code,c,b.data.exfields):p("",c,null,a)},function(b){console.log("error load template rpt",b.data);p("",c,null,a)}):p("",c,null,a)):p("",c,null,a)},function(b){p("",c,null,a)}))},initTemplate:t,chooseTemplate:v}}]);appInfoService.factory("vPrint",["printFactory",function(a){return a.loadTemplate}]);
appInfoService.factory("Base64",function(){return{encode:function(a){var e="",f,d,b,h,c,g,l=0;do f=a.charCodeAt(l++),d=a.charCodeAt(l++),b=a.charCodeAt(l++),h=f>>2,f=(f&3)<<4|d>>4,c=(d&15)<<2|b>>6,g=b&63,isNaN(d)?c=g=64:isNaN(b)&&(g=64),e=e+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);
while(l<a.length);return e},decode:function(a){var e="",f,d,b,h,c,g=0;/[^A-Za-z0-9\+\/\=]/g.exec(a)&&alert("There were invalid base64 characters in the input text.\nValid base64 characters are A-Z, a-z, 0-9, '+', '/',and '='\nExpect errors in decoding.");a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");do f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),
c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),f=f<<2|d>>4,d=(d&15)<<4|h>>2,b=(h&3)<<6|c,e+=String.fromCharCode(f),64!=h&&(e+=String.fromCharCode(d)),64!=c&&(e+=String.fromCharCode(b));while(g<a.length);return e}}});
var initLabel=function(a,e,f,d,b){e.STP=a.STP;a.ui_dropdowns={};e.turnOffDropdown=function(b){for(var c in a.ui_dropdowns)c===b&&a.Ui.turnOff(c)};e.toggleDropdown=function(b){if(a.Ui.active(b))a.Ui.turnOff(b);else{for(var c in a.ui_dropdowns)a.Ui.turnOff(c);a.Ui.turnOn(b);a.ui_dropdowns={};a.ui_dropdowns[b]=!0}};e.code=d;f.label(d,function(f){e.labels=f;e.getLabel=function(c,f){return getLabel(e.labels,c,f,a.lang,b,d.toUpperCase())}})},getLabel=function(a,e,f,d,b,h){h||(h="SYS");a&&_.isObject(a)||
(a={});var c=a[e.toUpperCase()];c&&c.texte||(c={labelid:h,textid:e,texte:f,textv:f},a[e.toUpperCase()]=c);b&&!c._id&&c.textv&&c.texte&&_online&&(a={},_.extend(a,c),c._id="TMP",b.post(server_url+"/api/labelinfo",a).then(function(a){c._id=a.data._id},function(a){}));c.text="EN"==d?c.texte:c.textv;return c},dateTime2Date=function(a){return a};
