var $jscomp={scope:{},findInternal:function(c,m,h){c instanceof String&&(c=String(c));for(var d=c.length,l=0;l<d;l++){var k=c[l];if(m.call(h,k,l,c))return{i:l,v:k}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,m,h){if(h.get||h.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[m]=h.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,m,h,d){if(m){h=$jscomp.global;c=c.split(".");for(d=0;d<c.length-1;d++){var l=c[d];l in h||(h[l]={});h=h[l]}c=c[c.length-1];d=h[c];m=m(d);m!=d&&null!=m&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:m})}};
$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,h){return $jscomp.findInternal(this,c,h).v}},"es6-impl","es3");
var baseService=function(c,m,h,d,l){var k,r={list:function(n,g,b,a,e,f,t,q,u,l){l&&(d=l);n=h("list")+"?t=1";1==a&&(n+="&count=1");e&&(n=n+"&page="+e.toString());f&&(n=n+"&limit="+f.toString());if(angular.isObject(g)){var p={};_.extend(p,g);t&&_.extend(p,t);u&&_.extend(p,u);q&&q(p,g);a=JSON.stringify(p);n=n+"&q="+encodeURIComponent(a)}else"$text"==d&&g?n=n+"&$text="+encodeURIComponent(JSON.stringify(g)):(p={},u&&_.extend(p,u),g&&d&&0!=d.length?(p.$or=[],d.forEach(function(a){var b={};b[a]={$regex:g,
$options:"i"};p.$or.push(b)})):t&&_.extend(p,t),q&&q(p,g),n=n+"&q="+encodeURIComponent(JSON.stringify(p)));b&&(n=n+"&fields="+b);k=m.defer();return c.get(n,{timeout:k.promise})},next:function(d,g){return c.get(h()+"/next/"+g)},get:function(d,g){return c.get(h()+"/"+g)},create:function(d,g){return c.post(h(),g)},update:function(d,g,b){return c.put(h()+"/"+g,b)},delete:function(d,g){return c.delete(h()+"/"+g)},getSocai:function(d,g){return c.get(h("report")+"/socai/"+g)},getVsocai:function(d,g){return c.get(h("report")+
"/vsocai/"+g)},load:function(c,d){return d?r.list(c,d.condition,d.fields,d.count,d.page,d.limit,d.queryParams,d.onCondition,d.filter,d.fields_find):r.list(c)},load2:function(c,d){return{cancel:function(b){k.resolve(b)},promise:r.load(c,d)}}};l&&_.extend(r,l(c));return r},baseService2=function(c,m,h,d,l,k,r){var n,g={list:function(b,a,e,c,d,q,g,v,p,w){w&&(k=w);b=l("list")+"?t=1";_.isObject(a)&&a.sync_from_date&&(b=l("report")+"?t=1");1==c&&(b+="&count=1");d&&(b=b+"&page="+d.toString());q&&(b=b+"&limit="+
q.toString());if(angular.isObject(a)){var f={};_.extend(f,a);g&&_.extend(f,g);p&&_.extend(f,p);v&&v(f,a);c=JSON.stringify(f);b=b+"&q="+encodeURIComponent(c)}else"$text"==k&&a?b=b+"&$text="+encodeURIComponent(JSON.stringify(a)):(f={},p&&_.extend(f,p),a&&k&&0!=k.length?(f.$or=[],k.forEach(function(b){var c={};c[b]={$regex:a,$options:"i"};f.$or.push(c)})):g&&_.extend(f,g),v&&v(f,a),b=b+"&q="+encodeURIComponent(JSON.stringify(f)));e&&(b=b+"&fields="+e);n=h.defer();return m.get(b,{timeout:n.promise})},
next:function(b,a){return m.get(l()+"/next/"+a)},get:function(b,a){var e=h.defer(),f=c.getCacheFactory(b,d,k);_online?m.get(l()+"/"+a).then(function(f){c.getCacheFactory(b,d,k).put(a,f.data);e.resolve(f)},function(b){b.data?e.reject(b):f.get(a,function(a,b){b?e.resolve({data:b}):a?e.reject({data:a}):e.reject({data:"KH\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7. H\u00e3y ki\u1ec3m tra l\u1ea1i internet c\u1ee7a b\u1ea1n"})})}):f.get(a,function(a,b){b?e.resolve({data:b}):a?e.reject({data:a}):
e.reject({data:"KH\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7. H\u00e3y ki\u1ec3m tra l\u1ea1i internet c\u1ee7a b\u1ea1n"})});return e.promise},create:function(b,a){var e=h.defer();_online?(delete a.name_service_need_sync,delete a._id,m.post(l(),a).then(function(a){c.getCacheFactory(b,d,k).put(a.data._id,a.data);e.resolve(a)},function(f){f.data?e.reject(f):(a.tmp_id?a._id=a.tmp_id:(a._id=d+"$$"+(new Date).getTime().toString(),a.tmp_id=a._id),a.name_service_need_sync=d,c.getCacheFactory(b,
"tempData").put(a._id,a,function(f,q){f?(c.getCacheFactory(b,"tempData").remove(a._id),c.getCacheFactory(b,d,k).remove(a._id),e.reject({data:f})):(c.getCacheFactory(b,d,k).put(a._id,a),e.resolve({data:a}))}))})):(a._id=d+"$$"+(new Date).getTime().toString(),a.tmp_id=a._id,a.name_service_need_sync=d,c.getCacheFactory(b,"tempData").put(a._id,a,function(f,g){f?(c.getCacheFactory(b,"tempData").remove(a._id),c.getCacheFactory(b,d,k).remove(a._id),e.reject({data:f})):(c.getCacheFactory(b,d,k).put(a._id,
a),e.resolve({data:a}))}));return e.promise},update:function(b,a,e){var f=h.defer();if(_online){delete e.name_service_need_sync;var g;e.tmp_id==a?(delete e._id,g=m.post(l()+"/"+a,e)):g=m.put(l()+"/"+a,e);g.then(function(a){c.getCacheFactory(b,"tempData").remove(e._id);e.tmp_id&&(c.getCacheFactory(b,"tempData").remove(e.tmp_id),c.getCacheFactory(b,d,k).remove(e.tmp_id));c.getCacheFactory(b,d,k).put(a.data._id,a.data);f.resolve(a)},function(g){g.data?f.reject(g):(e._id||(e._id=a),e.name_service_need_sync=
d,c.getCacheFactory(b,"tempData").put(a,e,function(g,h){g?(c.getCacheFactory(b,"tempData").remove(a),c.getCacheFactory(b,d,k).remove(a),f.reject({data:g})):(c.getCacheFactory(b,d,k).put(a,e),f.resolve({data:e}))}))})}else e.name_service_need_sync=d,c.getCacheFactory(b,"tempData").put(a,e,function(g,h){g?(c.getCacheFactory(b,"tempData").remove(a),c.getCacheFactory(b,d,k).remove(a),f.reject({data:g})):(c.getCacheFactory(b,d,k).put(a,e),f.resolve({data:e}))});return f.promise},delete:function(b,a){var e=
h.defer();_online?m.delete(l()+"/"+a).then(function(f){c.getCacheFactory(b,d,k).remove(a);e.resolve(f)},function(f){f.data?e.reject(f):c.getCacheFactory(b,"tempData_deleted").put(a,{_id:a,name_service:d},function(f){f?e.reject({data:f}):(c.getCacheFactory(b,d,k).remove(a),e.resolve({data:1}))})}):c.getCacheFactory(b,"tempData_deleted").put(a,{_id:a,name_service:d},function(f){f?e.reject({data:f}):(c.getCacheFactory(b,d,k).remove(a),e.resolve({data:1}))});return e.promise},deleteAll:function(b){var a=
h.defer();_online?m.delete(l()+"/a/delete/all").then(function(e){c.getCacheFactory(b,d,k).destroy();a.resolve(e)},function(b){b.data?a.reject(b):a.reject({data:"Ch\u1eafc n\u0103ng n\u00e0y c\u1ea7n c\u00f3 internet \u0111\u1ec3 th\u1ef1c hi\u1ec7n"})}):a.reject({data:"Ch\u1eafc n\u0103ng n\u00e0y c\u1ea7n c\u00f3 internet \u0111\u1ec3 th\u1ef1c hi\u1ec7n"});return a.promise},getSocai:function(b,a){return m.get(l("report")+"/socai/"+a)},getSokho:function(b,a){return m.get(l("report")+"/sokho/"+a)},
filterOffline:function(b,a){a||(a={condition:""});var e=h.defer();if(a.count)return e.resolve({data:{rows_number:0}}),e.promise;var f=d;a&&a.cacheName&&(f=a.cacheName);b=c.getCacheFactory(b,f,k);var g;a.condition&&(_.isObject(a.condition)?(g=a.condition.value_for_find,delete a.condition.value_for_find):g=a.condition);b.find(k,g,function(b,c){if(b)return e.reject({data:b});0!==c.length&&(b={},a.filter&&_.extend(b,a.filter),a.queryParams&&_.extend(b,a.queryParams),_.isObject(a.condition)&&_.extend(b,
a.condition),c=_.where(c,b));e.resolve({data:c})});return e.promise},load:function(b,a){var e=c.getCacheFactory(b,d,k),f=h.defer();_online?(a?g.list(b,a.condition,a.fields,a.count,a.page,a.limit,a.queryParams,a.onCondition,a.filter,a.fields_find):g.list(b)).then(function(b){f.resolve(b);a&&(a.count||a.fields)||async.mapSeries(b.data,function(a,b){a._id?e.put(a._id.toString(),a,function(c,e){if(c)return b(c);c=[a.picture,a.picture_thumb];a.exfields&&(c.push(a.exfields.picture),c.push(a.exfields.picture_thumb));
async.mapSeries(c,function(a,c){if(a&&"APP"!==_platform)try{ImgCache.cacheFile(server_url+a,function(){console.log("Cached image",a);b()})}catch(x){console.error("error cache image",a),b()}else b()},function(a,c){b(a)})}):b()},function(a,b){a&&c.toast("Can't cache data for offline, error:"+a)})},function(c){c.data?f.reject(c.data):g.filterOffline(b,a).then(function(a){f.resolve(a)})}):g.filterOffline(b,a).then(function(a){f.resolve(a)});return f.promise},load2:function(b,a){return{cancel:function(a){n.resolve(a)},
promise:g.load(b,a)}},logs:function(b,a,c){b=l("report")+"/g/log/"+a+"?t=1";c&&(c.user&&(b=b+"&user="+c.user),c.tu_ngay&&(c.tu_ngay=new Date(c.tu_ngay),b=b+"&tu_ngay="+moment(c.tu_ngay).format("YYYY-MM-DD")),c.den_ngay&&(c.den_ngay=new Date(c.den_ngay),b=b+"&den_ngay="+moment(c.den_ngay).format("YYYY-MM-DD")));return m.get(b)}};r&&_.extend(g,r(m));return g};
