var $jscomp={scope:{},checkStringArgs:function(b,h,c){if(null==b)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(h instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return b+""}};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,h,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[h]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,h,c,e){if(h){c=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var p=b[e];p in c||(c[p]={});c=c[p]}b=b[b.length-1];e=c[b];h=h(e);h!=e&&null!=h&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:h})}};
$jscomp.polyfill("String.prototype.endsWith",function(b){return b?b:function(b,c){var e=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===c&&(c=e.length);c=Math.max(0,Math.min(c|0,e.length));for(var h=b.length;0<h&&0<c;)if(e[--c]!=b[--h])return!1;return 0>=h}},"es6-impl","es3");
var baseRpt=function(b,h,c,e){b=b.toLowerCase();STPModules[b]={obj:this,type:"RPT"};this.rptId=b;var p=b+"Module";_.contains(modulesD,p)||modulesD.push(p);this.rptModuleName=p;this.module=angular.module(this.rptModuleName,["ngRoute"]);e||(e={});e.onInit&&(this.init=e.onInit);e.onAfterLoadData&&(this.afterLoadData=e.onAfterLoadData);e.onFetchData&&(this.fetchData=e.onFetchData);e.onDefaultCondition&&(this.defaultCondition=e.onDefaultCondition);e.onPrepareCondition&&(this.prepareCondition=e.onPrepareCondition);
this.getUrl=function(){return 0==e.require_id_app?server_url_report+"/public/"+h:server_url_report+"/api/"+id_app+"/"+h};this.module.factory(b+"Config",function(){return{}});this.getData=function(e,a,c,g,d,l,h){var f;l&&(f=l.getCacheFactory(id_app,"report"));var k=STPModules[b].obj.getUrl()+"?t=1";d&&(d.error="",d.$emit("$dataChangeStart"),d.running=!0);c&&angular.forEach(c,function(a,b){angular.isDate(a)?(a=moment(a).endOf("date").toDate(),a=JSON.stringify(a).replace(/\"/g,"")):angular.isObject(a)&&
(a=JSON.stringify(a));a&&(k=k+"&"+b+"="+encodeURIComponent(a))});if(_online)h&&window.fetch?fetch(k+"&access_token="+access_token+"&jsonstream=1").then(function(a){var b=a.body.getReader(),e=new TextDecoder,c="";b.read().then(function q(a){if(!a.done)return d.$apply(function(){var b=e.decode(a.value,{stream:!0});if(0<=b.indexOf("error")){d.$emit("$dataChangeError");d.running=!1;try{return g(JSON.parse(b).error)}catch(x){return g(b)}}if("running"===b)console.log("program is streaming....");else if(c+=
b,c.endsWith("$$end%")){var f=c.split("$$end%");async.map(f,function(a,b){if(a)try{g(null,JSON.parse(a)),b()}catch(z){b(a)}else b()},function(a,b){a&&console.log("error parse data",f,a)});c=""}}),b.read().then(q)}).then(function(){d.$apply(function(){d.$emit("$dataChangeSuccess");d.running=!1})})}).catch(function(a){console.log("error fetch data",a);d.$apply(function(){d.$emit("$dataChangeError");d.running=!1;if(a){var b="L\u1ed7i: ",b=a.message?b+a.message:b+a;g(b)}else g("Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7")})}):
e.get(k,{timeout:18E5}).then(function(a){a=a.data;if(f)try{f.put(k,a),console.log("CACHED REPORT",k)}catch(v){console.log("can't cache report",v,k)}d&&(d.$emit("$dataChangeSuccess"),d.running=!1);STPModules[b].obj.fetchData&&STPModules[b].obj.fetchData(k,a);g(null,a)},function(a){console.log("error fetch data",a.data);a=a.data;d&&(d.$emit("$dataChangeError"),d.running=!1);if(a){var b="L\u1ed7i: ",b=a.message?b+a.message:b+JSON.stringify(a);g(b)}else g("Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7")});
else if(f)console.log("GET DATA FROM CACHED REPORT",k),f.get(k,function(a,c){c?(d&&(d.$emit("$dataChangeSuccess"),d.running=!1),STPModules[b].obj.fetchData&&STPModules[b].obj.fetchData(k,c),g(null,c)):(d&&(d.$emit("$dataChangeError"),d.running=!1),g("B\u1ea1n \u0111ang ngo\u1ea1i tuy\u1ebfn. B\u00e1o c\u00e1o n\u00e0y c\u1ea7n k\u1ebft n\u1ed1i internet \u0111\u1ec3 l\u1ea5y d\u1eef li\u1ec7u"))});else return d&&(d.$emit("$dataChangeError"),d.running=!1),g("B\u1ea1n \u0111ang ngo\u1ea1i tuy\u1ebfn. B\u00e1o c\u00e1o n\u00e0y c\u1ea7n k\u1ebft n\u1ed1i internet \u0111\u1ec3 l\u1ea5y d\u1eef li\u1ec7u")};
this.module.controller(b+"Controller",["$localStorage","$scope","$http","$filter","$location",b+"Config","$controller","$rootScope","$window","appInfo","$uibModal","excel","vPrint",function(h,a,f,g,d,l,n,m,k,p,v,w,y){initLabel(m,a,p,b,f);a.rptId=b;a.isView||(m.function_title=c,m.function_code=b);a.forms={};k=d.search();var u=b;id_app&&(u+=id_app);if(a.condition||a.isView)a.condition.isDrillDown=!0;else{a.condition=h.getObject(u,{});if(!a.condition||_.isEqual(a.condition,{}))a.condition={},STPModules[b].obj.defaultCondition&&
STPModules[b].obj.defaultCondition(a.condition);if(_.isEqual(k,{})&&l.condition)for(var q in l.condition)d.search(q,l.condition[q]),k[q]=l.condition[q];_.extend(a.condition,k)}STPModules[b].obj.init&&STPModules[b].obj.init(a,f,g,d,l,n);p.info(b,function(k,p,q){if(!k){a.appInfo=q;a.title=c;!a.isView&&l.id_app==id_app&&_.isEqual(a.condition,l.condition)&&(a.data=l.data);a.data?(a.condition_show=!1,STPModules[b].obj.afterLoadData&&STPModules[b].obj.afterLoadData(a,a.data)):a.condition_show=!0;a.viewVoucher=
function(b,d){b&&d&&m.openUrl(b.toLowerCase(),{_id:d,_action:"edit"},function(){a.getData()})};a.order=function(b,d){a.data=g("orderBy")(a.data,b,d)};var x=e.stream?1E7:50;a.limit=x;a.begin=0;a.loadPage=function(){a.limit+=10};a.getData=function(){a.limit=x;if(e.onStartGetData)e.onStartGetData(a,function(b){b?m.alert(b):a.getDataFromServer()});else a.getDataFromServer()};a.getDataFromServer=function(){d.$$search={};if(!a.isView){h.setObject(u,a.condition);for(var c in a.condition){var k=a.condition[c];
angular.isDate(k)&&(k=g("date")(k,"yyyy-MM-dd"));k&&""!=k&&d.search(c,k)}}STPModules[b].obj.prepareCondition?STPModules[b].obj.prepareCondition(a.condition,g,function(t,c){t?a.error=t:(a.data=[],STPModules[b].obj.getData(f,g,c,function(t,c){c?(_.isArray(c)?a.data=a.data.concat(c):a.data.push(c),STPModules[b].obj.afterLoadData&&STPModules[b].obj.afterLoadData(a,a.data)):(a.error=t,t||(a.condition_show=!1,a.isView||(l.condition=d.search(),l.data=c,l.id_app=id_app)))},a,m,e.stream))}):(a.data=[],STPModules[b].obj.getData(f,
g,a.condition,function(t,c){c?(_.isArray(c)||(c=[c]),a.data=c.concat(a.data),STPModules[b].obj.afterLoadData&&STPModules[b].obj.afterLoadData(a,a.data)):(a.error=t,t||(a.condition_show=!1,a.isView||(l.condition=d.search(),l.data=c,l.id_app=id_app)))},a,m,e.stream))};a.exportExcel=function(d){if(_online){var e=STPModules[b].obj.getUrl()+"/excel?access_token="+access_token;STPModules[b].obj.prepareCondition?STPModules[b].obj.prepareCondition(a.condition,g,function(b,d){b?a.error=b:(angular.forEach(d,
function(a,b){angular.isDate(a)&&(a=g("date")(a,"yyyy-MM-dd"));angular.isObject(a)&&(a=JSON.stringify(a));a&&(e=e+"&"+b+"="+encodeURI(a))}),m.toast("Ch\u01b0\u01a1ng tr\u00ecnh \u0111ang th\u1ef1c hi\u1ec7n. Anh(ch\u1ecb) h\u00e3y ch\u1edd \u0111\u1ee3i trong gi\u00e2y l\u00e1t."),m.downloadFile(e,c+".xlsx",function(a){a&&(console.log(a),w.tableToExcel("#exportable","Report"))}))}):(angular.forEach(a.condition,function(a,b){angular.isDate(a)&&(a=g("date")(a,"yyyy-MM-dd"));angular.isObject(a)&&(a=
JSON.stringify(a));a&&(e=e+"&"+b+"="+encodeURI(a))}),m.toast("Ch\u01b0\u01a1ng tr\u00ecnh \u0111ang th\u1ef1c hi\u1ec7n. Anh(ch\u1ecb) h\u00e3y ch\u1edd trong gi\u00e2y l\u00e1t."),m.downloadFile(e,c+".xlsx",function(a){a&&(console.log(a),w.tableToExcel("#exportable","Report"))}))}else w.tableToExcel("#exportable","Report")};if(e.onLoading)e.onLoading(a,{$http:f,$filter:g,$location:d,$config:l,$controller:n,$rootScope:m});a.condition.isDrillDown&&(a.condition_show=!1,a.getData());a.isLike=!1;id_app&&
(f.get(server_url_report+"/api/"+id_app+"/like_module?q={module:'"+b+"'}").then(function(b){(b=b.data)&&1==b.length&&(a.isLike=b[0].like)},function(a){console.log(a.data)}),a.like=function(){f.post(server_url+"/api/"+id_app+"/like_module",{id_app:id_app,module:b,like:!0}).then(function(b){b.data&&(a.isLike=!0)},function(a){console.log(a.data)})},a.unlike=function(){f.post(server_url+"/api/"+id_app+"/like_module",{id_app:id_app,module:b,like:!1}).then(function(b){b.data&&(a.isLike=!1)},function(a){console.log(a.data)})});
a.$on("keydown",function(b,c){116==c.which?a.getData():c.ctrlKey&&(69==c.which?a.exportExcel():80==c.which&&a.print())});y(b,a);a.options=function(){var c=b,d="templates/reports/"+c+"/templates/options.html";v.open({templateUrl:"templates/sys/options-reports.html",controller:["$scope","$controller","$http","$uibModalInstance","$window","$localStorage","options","parentScope","vPrint",function(a,e,f,g,k,h,l,u,n){a.code=c;a.path=d;var r={},q=id_app+"_"+p.email+"_"+c+"_option";a.locals=h.getObject(q,
{});a.locals||(a.locals={system:{}});a.locals.system||(a.locals.system={});a.options={};l.load(id_app,{filter:{id_func:c}}).then(function(b){b=b.data;1==b.length?(r=b[0],a.options=r.option,a.options.check_so_ct||(a.options.check_so_ct="0")):(r.id_app=id_app,r.id_func=c)},function(a){console.log("error when load options",c,a.data)});a.changeWidthPage=function(b){if(a.options&&a.options.system&&a.options.system.templateRpt){var c=$(a.options.system.templateRpt);"printView"===c.attr("id")?(c.removeAttr("style"),
b&&(c.css("width",b+"mm"),c.css("margin","0px auto"))):c=b?$("<div id='printView' style='width: "+b+"mm; margin: 0px auto;'>"+a.options.system.templateRpt+"</div>"):$("<div id='printView'>"+a.options.system.templateRpt+"</div>");a.options.system.templateRpt=c[0].outerHTML}};a.save=function(){if(!a.isSave){a.isSave=!0;a.locals||(a.locals={});a.options&&a.options.system&&a.options.system.templateRpt&&(a.locals.system.templateRpt=a.options.system.templateRpt);try{h.setObject(q,a.locals)}catch(A){}r.option=
a.options;r._id?l.update(id_app,r._id,r).then(function(c){n(b,u);g.close();a.isSave=!1},function(b){m.toast(b.data+"<br/>Ch\u1ec9 nh\u1eefng t\u00f9y ch\u1ecdn theo ng\u01b0\u1eddi d\u00f9ng \u0111\u01b0\u1ee3c l\u01b0u.",null,null,null,"error");g.close();a.isSave=!1}):l.create(id_app,r).then(function(c){n(b,u);g.close();a.isSave=!1},function(b){m.toast(b.data+"<br/>Ch\u1ec9 nh\u1eefng t\u00f9y ch\u1ecdn theo ng\u01b0\u1eddi d\u00f9ng \u0111\u01b0\u1ee3c l\u01b0u.",null,null,null,"error");g.close();
a.isSave=!1})}};a.cancel=function(){g.close()}}],size:"sm",resolve:{parentScope:function(){return a}}})}}})}]);this.module.directive(b.split("_").join("")+"ReportView",[function(){return{restrict:"E",scope:{condition:"=?"},templateUrl:function(c,a){return"templates/reports/"+b+"/templates/"+(a.templateUrl?a.templateUrl:"browser")+".html"},controller:["$controller","$scope","$rootScope",function(c,a,e){a.isView=!0;c(b+"Controller",{$scope:a})}]}}]);this.quickview=function(e,a,f){e.open({template:function(){var a=
b.split("_").join("");return"<div  class='modal-header section-info'><button type='button' class='close' ng-click ='close()' aria-hidden='true'> &times;</button><h4 class='modal-title'>{{rpt_title}}</h4></div><div class='modal-body'><div style='height:{{innerHeight-60}}px'><"+a+"-report-view condition ='condition'></"+a+"-report-view></div></div>"},controller:["$rootScope","$scope","$controller","$uibModalInstance","appInfo","$http",function(e,d,h,n,m,k){initLabel(e,d,m,b,k);d.rpt_title=d.getLabel("ten_ct"+
b,c).text;d.rpt_code=b;d.condition=a;d.close=function(){f&&f();n.close()}}],size:"md",backdrop:"static",resolve:{}})};this.module.controller(b+"PrintController",["$controller","appInfo","$scope",b+"Config","$timeout","$location","$rootScope","$http",function(e,a,f,g,d,h,n,m){n.function_title=c;n.function_code=b;initLabel(n,f,a,b,m);a.info(b,function(a,l,m){a||(f.parameters={},f.condition=g.condition,f.title=c,f.data=g.data,f.appInfo=m,STPModules[b].obj.setParameters&&STPModules[b].obj.setParameters(f,
e),f.print=function(){f.printing=!0;n.printing=!0;d(function(){window.print();f.printing=!1;n.printing=!1},100)},f.back=function(){h.url("/"+b)},f.$on("keydown",function(a,b){b.ctrlKey&&80==b.which&&f.print()}))})}]);this.module.config(["$routeProvider","$locationProvider",function(c,a){c.when("/"+b,{templateUrl:"templates/reports/"+b+"/templates/browser.html",controller:b+"Controller",reloadOnSearch:!1}).when("/"+b+"/print",{templateUrl:"templates/reports/"+b+"/templates/print.html",controller:b+
"PrintController",reloadOnSearch:!1})}])};
