var $jscomp={scope:{},findInternal:function(b,k,c){b instanceof String&&(b=String(b));for(var h=b.length,d=0;d<h;d++){var g=b[d];if(k.call(c,g,d,b))return{i:d,v:g}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,k,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[k]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,k,c,h){if(k){c=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var d=b[h];d in c||(c[d]={});c=c[d]}b=b[b.length-1];h=c[b];k=k(h);k!=h&&null!=k&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:k})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6-impl","es3");
var baseVoucher=function(b,k,c,h,d){var g=this;d||(d={});c&&0!=c.length||(c=["so_ct","dien_giai","ma_kh","ten_kh"]);d.group="vouchers";d.modal_size||(d.modal_size="lg");g.watchMaster=d.onWatchMaster;g.defaultValues4Detail=d.onDefaultValues4Detail;g.watchDetail=d.onWatchDetail;g.tinhCkvt=function(a,b,l,d){if(l.ma_vt){var c=server_url_report+"/api/"+id_app+"/ckvt?ma_vt="+l.ma_vt;l.ma_tt1&&(c=c+"&ma_tt1="+l.ma_tt1);l.ma_tt2&&(c=c+"&ma_tt2="+l.ma_tt2);l.ma_tt3&&(c=c+"&ma_tt3="+l.ma_tt3);if(d||b.ma_kho||
l.ma_kho)c=c+"&ma_kho="+(d||b.ma_kho||l.ma_kho);b._id&&(c=c+"&id_ct="+b._id);a.get(c).then(function(a){0<a.data.length&&(l.ton_kho=a.data[0].ton)},function(a){l.ton_kho=0})}};var m=d.onLoading;d.onLoading=function(a,b){m&&m(a,b);a.updateSoCt=function(){b.$uibModal.open({templateUrl:"templates/sys/update-voucher-number.html",controller:["$scope","$rootScope","appInfo","$uibModalInstance","parentScope","$http",function(a,c,g,f,h,n){initLabel(c,a,g,"DBS",n);a.vcondition={tu_so:1,den_so:999999,tu_ngay:new Date,
den_ngay:new Date,post_again:!1};a.list=h.list;a.search=h.search;a.giaodichs=d.giaodichs;a.running=!1;a.okFind=function(){var e=server_url+"/api/"+id_app+"/"+k;a.vcondition.post_again?(e=e+"/action/postagain?tu_so="+a.vcondition.tu_so,e=e+"&den_so="+a.vcondition.den_so,a.vcondition.ma_gd&&(e=e+"&ma_gd="+a.vcondition.ma_gd),e=e+"&tu_ngay="+b.$filter("date")(a.vcondition.tu_ngay,"yyyy-MM-dd"),e=e+"&den_ngay="+b.$filter("date")(a.vcondition.den_ngay,"yyyy-MM-dd"),a.vcondition.tien_to&&(e=e+"&tien_to="+
a.vcondition.tien_to),a.vcondition.hau_to&&(e=e+"&hau_to="+a.vcondition.hau_to),a.running=!0,n.get(e).then(function(b){f.close();a.running=!1;c.alert("Ch\u01b0\u01a1ng tr\u00ecnh \u0111\u00e3 th\u1ef1c hi\u1ec7n xong")},function(b){a.running=!1;c.alert(b.data||"\u0110\u00e3 c\u00f3 l\u1ed7i x\u1ea3y . H\u00e3y li\u00ean h\u1ec7 v\u1edbi ng\u01b0\u1eddi qu\u1ea3n tr\u1ecb h\u1ec7 th\u1ed1ng \u0111\u1ec3 \u0111\u01b0\u1ee3c h\u1ed7 tr\u1ee3")})):(e=e+"/update/so_ct?tu_so="+a.vcondition.tu_so,e=e+"&den_so="+
a.vcondition.den_so,a.vcondition.ma_gd&&(e=e+"&ma_gd="+a.vcondition.ma_gd),e=e+"&tu_ngay="+b.$filter("date")(a.vcondition.tu_ngay,"yyyy-MM-dd"),e=e+"&den_ngay="+b.$filter("date")(a.vcondition.den_ngay,"yyyy-MM-dd"),a.vcondition.tien_to&&(e=e+"&tien_to="+a.vcondition.tien_to),a.vcondition.hau_to&&(e=e+"&hau_to="+a.vcondition.hau_to),a.running=!0,n.get(e).then(function(b){a.running=!1;f.close();a.search();c.alert("Ch\u01b0\u01a1ng tr\u00ecnh \u0111\u00e3 th\u1ef1c hi\u1ec7n xong")},function(b){a.running=
!1;c.alert(b.data||"\u0110\u00e3 c\u00f3 l\u1ed7i x\u1ea3y . H\u00e3y li\u00ean h\u1ec7 v\u1edbi ng\u01b0\u1eddi qu\u1ea3n tr\u1ecb h\u1ec7 th\u1ed1ng \u0111\u1ec3 \u0111\u01b0\u1ee3c h\u1ed7 tr\u1ee3")}))};a.cancelFind=function(){f.close()}}],size:"lg",resolve:{parentScope:function(){return a}}})}};var p=d.onEdit;d.onEdit=function(a,c){p&&p(a,c);a.data.details||(a.data.details=[]);a.data.ma_ct=b.toUpperCase();g.watchMaster&&g.watchMaster(a,c);a.hideListProducts=!0;a.vPrint(b,a)};var q=d.onAdd;d.onAdd=
function(a,c){q&&q(a,c);a.data.ngay_ct||(a.data.ngay_ct=new Date,a.data.ma_nt||(a.data.ty_gia=1,a.data.ma_nt="VND"));a.data.details||(a.data.details=[]);a.data.so_ct||c.service.next(id_app,"so_ct").then(function(b){a.data.so_ct=b.data.so_ct},function(a){console.log(a.data)});a.data.ma_ct=b.toUpperCase();g.watchMaster&&g.watchMaster(a,c);a.vPrint(b,a)};baseInput.call(this,b,k,c,h,d);g.module.directive(b.split("_").join("")+"DetailTable",function(){return{restrict:"E",scope:{ngMasterData:"=",onChange:"&?"},
templateUrl:"templates/vouchers/"+b+"/templates/detail-table.html",controller:["$scope","$uibModal","$timeout","$http","$window","$rootScope","appInfo",function(a,c,d,h,k,f,m){initLabel(f,a,m,b,h);a.status={isOpened:!1};a.$uibModal=c;a.$http=h;a.$window=k;a.STP=STP;a.openUrl=f.openUrl;a.app_info=f.app_info;a.f_sl=f.app_info.options.f_sl||2;a.f_ty_gia=f.app_info.options.f_ty_gia||0;a.f_gia=f.app_info.options.f_gia||0;a.f_tien=f.app_info.options.f_tien||0;1==a.ngMasterData.ty_gia?(a.f_gia_nt=f.app_info.options.f_gia||
0,a.f_tien_nt=f.app_info.options.f_tien||0):(a.f_gia_nt=f.app_info.options.f_gia_nt||2,a.f_tien_nt=f.app_info.options.f_tien_nt||2);a.round=a.f_tien_nt;a.tinhCkvt=function(b,c){g.tinhCkvt(h,a.ngMasterData||a.data,b,c)};a.$watch("ngMasterData.ty_gia",function(b,c){1==a.ngMasterData.ty_gia?(a.f_gia_nt=f.app_info.options.f_gia||0,a.f_tien_nt=f.app_info.options.f_tien||0):(a.f_gia_nt=f.app_info.options.f_gia_nt||2,a.f_tien_nt=f.app_info.options.f_tien_nt||2);a.round=a.f_tien_nt});g.watchDetail&&g.watchDetail(a,
{$rootScope:f,$http:h});a.isNotRowSelected=function(a){return 0==_.filter(a,function(a){return 1==a.sel}).length};a.deleteRow=function(a){var b=_.reject(a,function(a){return 1==a.sel}),c=a.length=0;b.forEach(function(b){b.line=c;a.push(b);c++})};a.delete1Row=function(b){var c=_.reject(a.ngMasterData.details,function(a){return a.line===b.line}),d=a.ngMasterData.details.length=0;c.forEach(function(b){b.line=d;a.ngMasterData.details.push(b);if(a.onChange)a.onChange({$item:b});d++})};a.addDetail=function(){var b=
a.ngMasterData.details.length;a.dt_master=null;a.dt_current={line:b};g.defaultValues4Detail&&_.extend(a.dt_current,g.defaultValues4Detail);a.ngMasterData.options&&_.extend(a.dt_current,a.ngMasterData.options);a.ngMasterData.details||(a.ngMasterData.details=[]);a.openDetail("md")};a.editDetail=function(b){a.dt_master=_.find(a.ngMasterData.details,function(a){return a.line==b});a.dt_current={};_.extend(a.dt_current,a.dt_master);a.openDetail("md")};a.openDetail=function(f,e){f=c.open({templateUrl:"templates/vouchers/"+
b+"/templates/detail-edit.html",controller:["$scope","$uibModalInstance","parentScope","$rootScope","$http",function(a,b,c,d,e){g.watchDetail&&g.watchDetail(a,{$rootScope:d,$http:e});a.tinhCkvt=c.tinhCkvt;a.data=a.ngMasterData=c.ngMasterData;a.status=c.status;a.STP=STP;a.round=c.round;a.f_sl=c.f_sl;a.f_gia=c.f_gia;a.f_tien=c.f_tien;a.f_ty_gia=c.f_ty_gia;a.f_gia_nt=c.f_gia_nt;a.f_tien_nt=c.f_tien_nt;a.dt_master=c.dt_master;a.dt_current=c.dt_current;a.app_info=c.app_info;a.updateDetail=function(){a.dt_master||
(a.dt_master={},a.data.details.push(a.dt_master));for(var c in a.dt_current)a.dt_master[c]=a.dt_current[c];b.close()};a.cancelDetail=function(){b.close()}}],size:f,resolve:{parentScope:function(){return a}}});f.opened.then(function(){d(function(){a.status.isOpened=!0},300)});f.result.then(function(b){a.status.isOpened=!1},function(){a.status.isOpened=!1})}}],link:function(a,b,c,d){}}})};baseVoucher.prototype=new baseInput;
