var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var d=0;return $jscomp.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,g={next:function(){if(f<a.length){var h=f++;return{value:d(h,a[h]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(a,d,f,g){if(d){f=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var h=a[g];h in f||(f[h]={});f=f[h]}a=a[a.length-1];g=f[a];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
angular.module("ui.calendar",[]).constant("uiCalendarConfig",{calendars:{}}).controller("uiCalendarCtrl",["$scope","$locale","$uibModal",function(a,d,f){var g=a.eventSources,h=a.calendarWatchEvent?a.calendarWatchEvent:angular.noop,k=function(b){return function(){if(a.$root.$$phase)return b.apply(this,arguments);var c=arguments,n=this;return a.$root.$apply(function(){return b.apply(n,c)})}},e=1;this.eventFingerprint=function(b){b._id||(b._id=e++);var c=h({event:b})||"",a=moment.isMoment(b.start)?b.start.unix():
b.start?moment(b.start).unix():"",d=moment.isMoment(b.end)?b.end.unix():b.end?moment(b.end).unix():"";return[b._id,b.id||"",b.title||"",b.url||"",a,d,b.allDay||"",b.className||"",c].join("")};var l=1,m=1;this.sourceFingerprint=function(b){var c=""+(b.__id||(b.__id=l++));if(b=angular.isObject(b)&&b.events)c=c+"-"+(b.__id||(b.__id=m++));return c};this.allEvents=function(){return Array.prototype.concat.apply([],(g||[]).reduce(function(b,c){if(angular.isArray(c))b.push(c);else if(angular.isObject(c)&&
angular.isArray(c.events)){var a=Object.keys(c).filter(function(c){return"_id"!==c&&"events"!==c});c.events.forEach(function(c){angular.extend(c,a)});b.push(c.events)}return b},[]))};this.changeWatcher=function(a,c){var b,d=function(){return((angular.isFunction(a)?a():a)||[]).reduce(function(a,b){var d=c(b);g[d]=b;a.push(d);return a},[])},e=function(a,c){var b=(c||[]).reduce(function(a,c){a[c]=!0;return a},Object.create(null));return(a||[]).filter(function(a){return!b[a]})},g={};return b={subscribe:function(a,
n){a.$watch(d,function(a,d){if(!n||!1!==n(a,d)){var f,h={},q=e(d,a);for(f=0;f<q.length;f++){var p=q[f],k=g[p];delete g[p];var l=c(k);if(l===p)b.onRemoved(k);else h[l]=p,b.onChanged(k)}d=e(a,d);for(f=0;f<d.length;f++)if(a=d[f],!h[a])b.onAdded(g[a])}},!0)},onAdded:angular.noop,onChanged:angular.noop,onRemoved:angular.noop}};this.getFullCalendarConfig=function(a,c){var b={};angular.extend(b,c);angular.extend(b,a);angular.forEach(b,function(a,c){"function"===typeof a&&(b[c]=k(b[c]))});return b};this.getLocaleConfig=
function(a){if(!a.lang&&!a.locale||a.useNgLocale){a=function(a){return(Object.keys(a)||[]).reduce(function(c,b){c.push(a[b]);return c},[])};var c=d.DATETIME_FORMATS;return{monthNames:a(c.MONTH),monthNamesShort:a(c.SHORTMONTH),dayNames:a(c.DAY),dayNamesShort:a(c.SHORTDAY)}}return{}};a.chooseMonthYear=function(a){f.open({templateUrl:"templates/sys/choosemotnhandyear.html",controller:["$scope","$controller","$http","$uibModalInstance","$rootScope",function(c,b,d,e,f){b=a.fullCalendar("getDate");c.month=
b.month()+1;c.year=b.year();c.months=[1,2,3,4,5,6,7,8,9,10,11,12];c.ok=function(){a.fullCalendar("gotoDate",new Date(c.year,c.month-1,1));e.close()};c.cancel=function(){e.close()}}],size:"lg",backdrop:"static",resolve:{}})}}]).directive("uiCalendar",["uiCalendarConfig",function(a){return{restrict:"A",scope:{eventSources:"=ngModel",zevents:"=",calendarWatchEvent:"&"},controller:"uiCalendarCtrl",link:function(d,f,g,h){var k=!1,e,l=h.changeWatcher(d.eventSources,h.sourceFingerprint),m=h.changeWatcher(h.allEvents,
h.eventFingerprint),b=null;d.destroyCalendar=function(){e&&e.fullCalendar&&e.fullCalendar("destroy");e=g.calendar?a.calendars[g.calendar]=angular.element(f).html(""):angular.element(f).html("")};d.initCalendar=function(){e||(e=$(f).html(""));e.fullCalendar(b);g.calendar&&(a.calendars[g.calendar]=e);var c=document.querySelector(".fc-center");angular.element(c).bind("click",function(){d.chooseMonthYear(e)})};d.$on("$destroy",function(){d.destroyCalendar()});l.onAdded=function(c){e&&e.fullCalendar&&
(e.fullCalendar(b),g.calendar&&(a.calendars[g.calendar]=e),e.fullCalendar("addEventSource",c),k=!0)};l.onRemoved=function(a){e&&e.fullCalendar&&(e.fullCalendar("removeEventSource",a),k=!0)};l.onChanged=function(){e&&e.fullCalendar&&(e.fullCalendar("refetchEvents"),k=!0)};m.onAdded=function(a){e&&e.fullCalendar&&e.fullCalendar("renderEvent",a,!!a.stick)};m.onRemoved=function(a){e&&e.fullCalendar&&e.fullCalendar("removeEvents",a._id)};m.onChanged=function(a){if(e&&e.fullCalendar)for(var c=e.fullCalendar("clientEvents",
a._id),b=0;b<c.length;b++){var d=c[b],d=angular.extend(d,a);e.fullCalendar("updateEvent",d)}};l.subscribe(d);m.subscribe(d,function(){if(!0===k)return k=!1});d.$watch(function(){var c=g.uiCalendar?d.$parent.$eval(g.uiCalendar):{},c=h.getFullCalendarConfig(c,a),e=h.getLocaleConfig(c);angular.extend(e,c);b={eventSources:d.eventSources};angular.extend(b,e);b.calendars=null;var c={},f;for(f in b)"eventSources"!==f&&(c[f]=b[f]);return JSON.stringify(c)},function(a,b){a!==b?(d.destroyCalendar(),d.initCalendar()):
a&&angular.isUndefined(e)&&d.initCalendar()});d.$watch("zevents",function(a,b){a!==b&&(d.destroyCalendar(),d.initCalendar())},!0)}}}]);
