var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[g]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var g=0;return $jscomp.iteratorPrototype(function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,g){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,b={next:function(){if(f<a.length){var k=f++;return{value:g(k,a[k]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};
$jscomp.polyfill=function(a,g,f,b){if(g){f=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var k=a[b];k in f||(f[k]={});f=f[k]}a=a[a.length-1];b=f[a];g=g(b);g!=b&&null!=g&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,f){return f})}},"es6","es3");
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");$jscomp.findInternal=function(a,g,f){a instanceof String&&(a=String(a));for(var b=a.length,k=0;k<b;k++){var l=a[k];if(g.call(f,l,k,a))return{i:k,v:l}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6-impl","es3");
var id_app,access_token,cmdmodules,paths_not_require_id_app="code app colleague notification message profile users comment versioninfo labelinfo tableinfo license trialinfo admin rptobject trangthai step".split(" "),accApp=angular.module("accApp",modulesD);
accApp.config(["$provide","$httpProvider","$routeProvider","ImgCacheProvider","$compileProvider",function(a,g,f,b,k){b.setOption("debug",!1);b.setOption("chromeQuota",52428800);b.setOption("usePersistentCache",!0);b.manualInit=!0;k.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|chrome-extension):/);a.factory("myHttpInterceptor",["$q","$rootScope","$location",function(b,a,f){return{request:function(b){return b},requestError:function(a){return b.reject(a)},response:function(b){return b},responseEror:function(g){401===
g.status?(a.isLogined=!1,f.url("/login")):0!=g.status&&500!=g.status||a.error("Kh\u00f4ng k\u1ebft n\u1ed1i \u0111\u01b0\u1ee3c v\u1edbi m\u00e1y ch\u1ee7");return b.reject(g)}}}]);g.interceptors.push("myHttpInterceptor");f.otherwise({redirectTo:"/dashboard"})}]);accApp.constant("_",window._);accApp.constant("async",window.async);
accApp.factory("api",["$http","$localStorage","$rootScope",function(a,g,f){return{init:function(b){b||(b=g.get("token"));b?(f.isLogined=!0,f.token=b):f.isLogined=!1;access_token=b;a.defaults.headers.common["X-Access-Token"]=b}}}]);var _platform="APP",_online=!0;
accApp.run(["indexCache","toastrConfig","$q","$rootScope","api","$window","user","app","$location","$shttp","appInfo","$timeout","editableOptions","$uibModalStack","$localStorage","$cordovaDialogs","$cordovaToast","$cordovaDevice","$document","$uibModal","$cordovaStatusbar","$cordovaNetwork","ImgCache","toastr",function(a,g,f,b,k,l,F,G,m,n,u,v,y,z,r,A,B,C,H,p,w,D,E,t){b.online=navigator.onLine;_online=b.online;b.getCacheFactory=function(b,e,x,d){return a.getCacheFactory(b,e,d)};b.syncing=!1;b.sync=
function(a){a||(a=function(){});id_app&&b.app_info&&_online&&"APP"!=_platform&&!b[id_app+"sync"]?(b[id_app+"sync"]=!0,console.log("begin upload data to server..."),async.parallel({up:function(a){var c=b.getCacheFactory(id_app,"tempData");console.log("get values from tempData");c.values(function(e,h){if(e)return a();console.log("end get values from tempData",h);async.map(h,function(a,e){var q=a.name_service_need_sync;if(q){var d=server_url_report+"/api/"+id_app+"/"+q,h;h=a._id;a.tmp_id&&a.tmp_id===
a._id?(delete a._id,d=n.post(d,a)):(d=d+"/"+a._id,d=n.put(d,a));d.then(function(d){c.remove(h,function(){console.log("remove from temp",a,h)});b.getCacheFactory(id_app,q).remove(h);b.getCacheFactory(id_app,q).put(d.data._id,d.data);e()},function(d){d.data&&(c.remove(h),b.getCacheFactory(id_app,q).remove(h),console.log("error sync",d.data,a));e()})}else c.remove(a._id),b.getCacheFactory(id_app,q).remove(a._id),e()},function(b,c){b&&console.log("sync error",b);a()})})},del:function(a){var c=b.getCacheFactory(id_app,
"tempData_deleted");c.values(function(e,h){if(e)return a();async.map(h,function(a,e){var d=a.name_service;d&&0>a._id.indexOf("$$")?(console.log("begin delete sync",d,a._id),n.delete(server_url_report+"/api/"+id_app+"/"+d+"/"+a._id).then(function(h){console.log("finished delete sync",d,a._id);c.remove(a._id);b.getCacheFactory(id_app,d).remove(a._id);e()},function(h){h.data&&(console.log("error delete sync",d,a._id,h.data),c.remove(a._id),b.getCacheFactory(id_app,d).remove(a._id));e()})):(c.remove(a._id),
b.getCacheFactory(id_app,d).remove(a._id),e())},function(b,c){b&&console.log("sync delete error",b);a()})})}},function(c,g){if("zbrowser"===_platform)console.log("don't download data from server for",_platform),b[id_app+"sync"]=!1,a();else{console.log("begin download data from server...");var e="users versioninfo trialinfo license tableinfo forminfo".split(" "),h=new Date;b.sync_date=r.get(id_app+"sync_date");async.mapSeries(_.keys(STPModules),function(a,c){if(0>e.indexOf(a.toLowerCase())){var d=
STPModules[a];d.obj.download?async.parallel({del:function(a){var c={tu_ngay:b.sync_date};d.obj.getService(n,f,b).logs(id_app,"DELETE",c).then(function(c){async.mapSeries(c.data,function(a,c){b.getCacheFactory(id_app,a.id_func.toLowerCase()).remove(a.data.id);c()},function(b,c){a()})},function(b){b.data&&console.log(b.data);a()})},dow:function(a){d.obj.download(n,f,b,1E6,function(b){a()})}},function(b,a){c()}):c()}else c()},function(c,e){b[id_app+"sync"]=!1;r.set(id_app+"sync_date",h);a()})}})):a()};
document.addEventListener("deviceready",function(){E.$init();_platform=C.getPlatform();"function"==typeof require&&(_platform="nwjs");w.overlaysWebView(!0);w.styleHex("#34AADC");"browser"===_platform||"nwjs"===_platform?(_online=navigator.onLine,b.online=_online,l.addEventListener("offline",function(){b.$apply(function(){_online=b.online=!1})},!1),l.addEventListener("online",function(){b.$apply(function(){_online=b.online=!0;b.sync(function(){b.syncing=!1})})},!1)):(_online=D.isOnline(),b.online=
_online,b.$on("$cordovaNetwork:online",function(a,e){_online=b.online=!0;b.sync(function(){b.syncing=!1})}),b.$on("$cordovaNetwork:offline",function(a,e){_online=b.online=!1}));b.syncing=!0;v(function(){b.sync(function(){b.syncing=!1})},0)},!1);b.platform=function(){return _platform};b.isLogined=!1;b.program_name=MAIN_APPLICATION_NAME;b.version=2.5;b.alert=function(b,a,f){p.open({templateUrl:"templates/sys/alert.html",controller:["$scope","$rootScope","$uibModalInstance",function(c,e,g){c.dismiss=
function(){g.close()};c.msg=b;c.title=a;c.onClick=f||function(){}}],size:"sm"})};b.confirm=function(b){var a=f.defer();p.open({templateUrl:"templates/sys/confirm.html",controller:["$scope","$rootScope","$uibModalInstance",function(c,e,h){c.dismiss=function(){a.resolve(0);h.close()};c.ok=function(){a.resolve(1);h.close()};c.msg=b}],size:"sm",backdrop:"static"});return a.promise};b.prompt=function(a,e){return A.prompt(a,b.program_name,["Nh\u1eadn","Hu\u1ef7"],e)};angular.extend(g,{iconClasses:{error:"toast-error",
info:"toast-info",success:"toast-system",warning:"toast-warning"},positionClass:"toast-bottom-right",progressBar:!1,newestOnTop:!0,maxOpened:0,preventDuplicates:!1,preventOpenDuplicates:!1});b.toast=function(a,e,f,d,h){h||(h="info");var c;switch(h){case "error":c=t.error;break;case "warning":c=t.warning;break;case "success":c=t.success;break;default:c=t.info}var g={allowHtml:!0,closeButton:!0,timeOut:e||3E3,onTap:d};"android"===b.platform().toLowerCase()||"ios"===b.platform().toLowerCase()?B.showShortTop(a).then(function(b){},
function(b){c(a,"",g)}):c(a,"",g)};b.openDefaultInterface=function(){if(b.interface){var a=_.find(interfaces,function(a){return a.id===b.interface});a?m.url("/"+(a.default||"dashboard")):m.url("/dashboard")}else m.url("/dashboard")};b.openUrl=function(b,a,f,d){var c={};a&&_.extend(c,a);d&&_.extend(c,d);if(b){d=b.split("?")[0].split("/");var e=d[0];!e&&1<d.length?(e=d[1],a=2<d.length?d[2]:"",d=3<d.length?d[3]:""):(a=1<d.length?d[1]:"",d=2<d.length?d[2]:"");var g=STPModules[e.toLowerCase()];if(g)switch(e=
g.obj,"RPT"==g.type?(c.isDrillDown=!0,a="listview"):(a||(a=c._action),a||(a="listview")),_.extend(c,STP.queryStringToJSON(b)),delete c._action,a){case "listview":e.quickview(p,c,f);break;case "edit":d||(d=c._id);d&&e.quickedit(p,d,f);break;case "add":e.quickadd(p,f,c);break;default:m.url(b)}else console.log("not found module",e,b,c),m.url(b)}};b.downloadFile=function(a,e,f){var c;_.isObject(a)?(c=server_url_report+"/api/"+a.id_app+"/file/download/"+a._id+"?access_token="+b.token,e||(e=a.file.originalname)):
(c=a,e||(e="file"));n.get(c,{responseType:"arraybuffer"}).then(function(b){b=new Blob([b.data]);saveAs(b,e);f&&f()},function(a){f?f(a.data||"Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7"):a.data?b.alert(a.data):b.alert("Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7")})};b.innerHeight=l.innerHeight;b.innerWidth=l.innerWidth;b.isMobile=991>=b.innerWidth;angular.element(l).bind("resize",function(){b.innerHeight=l.innerHeight;b.innerWidth=l.innerWidth;b.isMobile=
991>=b.innerWidth});b.printS=function(a,e){e||(e=b.program_name||"");document.addEventListener("deviceready",function(){a='<html><head><style> @media print { @page { margin: 0}}</style><link rel="stylesheet" type="text/css" href="libs/bootstrap/dist/css/bootstrap.min.css" /><link rel="stylesheet" type="text/css" href="libs/semantic-ui-card/card.min.css" /><link rel="stylesheet" type="text/css" href="css/main.css" /><title>'+e+'</title></head><body style ="margin-top: 0.1cm;margin-bottom:0.1cm">'+
a+"</body></html>";if("browser"===_platform||"nwjs"===_platform)document.getElementById("printframe").contentWindow.document.documentElement.innerHTML=a,setTimeout(function(){window.frames.printframe.print()},500);else try{cordova.plugins.printer.print(a,"Document.html")}catch(x){b.toast(x)}},!1)};b.lang=r.get("lang");initLabel(b,b,u,"SYS",n);b.setLang=function(a){b.lang=a;r.set("lang",a);l.location.reload()};y.theme="bs3";n.get(server_url+"/public/province",{cache:!0}).then(function(a){b.province=
a.data});b.STP=STP;b.nextTick=function(b){v(b,0)};b.server_url=server_url;b.$watch("app_info",function(a,e){b.function_title?$("title").text(b.function_title+(b.app_info?" - "+b.app_info.name:"")):$("title").text(program_name);a&&!_.isEqual(a,e)&&(b.syncing=!0,v(function(){b.sync(function(){b.syncing=!1})},0),b.commands={},u.commands(b.id_app),b.app_info.user_created?(b.members=[{email:b.app_info.user_created,name:b.app_info.user_created.split("@")[0]}],b.app_info.participants.forEach(function(a){b.members.push({email:a.email,
name:a.name})})):b.members=[])},!0);b.$watch("function_title",function(a){a?$("title").text(b.function_title+(b.app_info?" - "+b.app_info.name:"")):$("title").text(program_name)});b.$on("$routeChangeStart",function(a,e){l.scrollTo(0,0);b.$broadcast("$dataChangeSuccess");z.dismissAll()});b.openPath=function(a,e){b.menuActive=e;m.url(a)};b.confDashboard=function(){u.confDashboard(b.app_info)};b.searchword="";b.searchAllKeyup=function(b,a){13===b.keyCode&&a&&m.url("search/"+a)};b.searchAll=function(a){a&&
m.url("search/"+a)};b.tinymceOptionsEmail={setup:function(a){a.addButton("hlink",{text:"Li\u00ean k\u1ebft n\u1ed9i b\u1ed9",icon:!1,onclick:function(){hlinkModule.quickview(p,{},function(){},{templateUrl:"hlinkview",onListItemClick:function(b,c){c.close();a.insertContent("<a href='"+(server_url+"/public/link/"+b._id+"/{{receiver._id}}?cid={{cid}}")+"'>"+b.name+"</a>")}})}});a.addButton("insertName",{text:"T\u00ean ng\u01b0\u1eddi nh\u1eadn",icon:!1,onclick:function(){a.insertContent("{{receiver.name}}")}});
a.addButton("insertAddress",{text:"Email ng\u01b0\u1eddi nh\u1eadn",icon:!1,onclick:function(){a.insertContent("{{receiver.address}}")}})},menubar:!1,relative_urls:!1,remove_script_host:!1,height:300,theme:"modern",toolbar_items_size:"small",content_css:"libs/bootstrap/dist/css/bootstrap.min.css",importcss_append:!0,paste_data_images:!1,paste_as_text:!1,plugins:["advlist autolink code fullscreen importcss link image lists hr anchor pagebreak","searchreplace visualblocks visualchars code media nonbreaking",
"table contextmenu directionality emoticons template textcolor paste  textcolor colorpicker textpattern"],toolbar1:"hlink insertName insertAddress | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | fontselect fontsizeselect | table | hr removeformat | searchreplace | bullist numlist | outdent indent blockquote | link unlink anchor image media| pagebreak | forecolor backcolor  | fullscreen code",image_advtab:!0,language:"vi_VN"};b.tinymceOptions={};_.extend(b.tinymceOptions,
b.tinymceOptionsEmail,{toolbar1:"bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | fontselect fontsizeselect | table | hr removeformat | searchreplace | bullist numlist | outdent indent blockquote | link unlink anchor image media | pagebreak | forecolor backcolor | fullscreen code"});k.init()}]);
