var dashboardModule=angular.module("dashboardModule",["ngRoute"]);
dashboardModule.controller("homeController",["$scope","$localStorage","user","$rootScope","$location","$timeout","$shttp","api","$window","$interval","appInfo","$uibModal","$filter","$routeParams","options",function(c,f,g,d,a,b,e,r,t,l,p,u,v,q,n){d.function_title="B\u1ea3ng \u0111i\u1ec1u khi\u1ec3n";d.function_code="dashboard";d.interface=f.get("interface");c.model={title:" ",structure:"4-8",rows:[]};initLabel(d,c,p,"DBC",e);q.invb&&f.set("partner",q.invb);if(!("/download"==a.url().toLowerCase()||
0<=a.url().toLowerCase().indexOf("/signup")||0<=a.url().toLowerCase().indexOf("/support"))){if(0<=a.url().indexOf("/~lg/")){d.chv=!0;b=a.url().split("/");var k="dashboard",h,m;if(4<=b.length&&(m=b[2],h=b[3],4<b.length))for(k="",e=4;e<b.length;e++)k=k?k+"/"+b[e]:b[e];if(m){f.set("token",m);f.set("id_app",h);r.init(m);g.getInfo(function(c){a.url("/"+k)});return}}f.get("token")?"/dashboard"!=a.url()&&"/"!=a.url()||p.info("/dashboard",function(b,d,f){if(b)a.url("/login");else{c.appInfo=f;var e,l;l="DASHBOARD-"+
d.email;n.load(h,{condition:{id_func:l}}).then(function(a){0<a.data.length?(c.model=a.data[0].option&&a.data[0].option.model?a.data[0].option.model:JSON.parse(JSON.stringify(dashboarModelDefault)),e=a.data[0]._id):c.model=JSON.parse(JSON.stringify(dashboarModelDefault))},function(a){console.log(a.data)});c.$on("adfDashboardChanged",function(a,c,b){b&&(e?n.update(h,e,{option:{model:b}}).then(function(a){console.log("updated dashboard options")},function(a){console.log("Error update dashboard options",
a.data)}):(console.log("create dashboard",b),n.create(h,{option:{model:b},id_app:h,id_func:l}).then(function(a){e=a.data._id},function(a){console.log("Error create dashboard options",a.data)})))})}}):(0>a.url().toLowerCase().indexOf("/login")&&0>a.url().toLowerCase().indexOf("/logout")&&0>a.url().toLowerCase().indexOf("/signup")&&(d.w_redirect=a.url()),a.url("/login"))}}]);dashboardModule.controller("dxdController",["$scope",function(c){}]);
dashboardModule.controller("adminController",["appInfo","$location","$rootScope","$scope","$http","$uibModal",function(c,f,g,d,a,b){g.function_title="Adminstrator";g.function_code="administrator";initLabel(g,d,c,"DSB",a);c.info("admin",function(c,g,t){c?f.url("/login"):d.broadcast=function(){b.open({templateUrl:"templates/dashboard/templates/broadcast.html",controller:["$scope","$rootScope","$uibModalInstance",function(b,c,d){b.msg={message:"",title:""};b.dismiss=function(){d.close()};b.send=function(){b.msg.message&&
b.msg.title&&a.post(server_url+"/api/notification/broadcast",b.msg).then(function(a){c.alert(a.data)},function(a){c.alert(a.data||"Can't connect to server")})}}],size:"sm",backdrop:"static"})}})}]);
dashboardModule.config(["$routeProvider","$locationProvider","$httpProvider",function(c,f,g){c.when("/",{templateUrl:"templates/dashboard/templates/db1.html",controller:"homeController"}).when("/lg/:id_app",{templateUrl:"templates/dashboard/templates/db1.html",controller:"homeController"}).when("/dxd",{templateUrl:"templates/dashboard/templates/dxd.html",controller:"dxdController"}).when("/admin",{templateUrl:"templates/dashboard/templates/admin.html",controller:"adminController"}).when("/dashboard",
{templateUrl:"templates/dashboard/templates/db1.html",controller:"homeController"})}]);
