var $jscomp={scope:{},findInternal:function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6-impl","es3");$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b,c){return c})}},"es6","es3");
accApp.directive("format",["$filter",function(a){return{require:"?ngModel",scope:{ngModel:"=",watchChange:"&?",round:"=?"},controller:["$scope",function(b){b.$watch("ngModel",function(c){void 0==c?b.ngModel=0:b.watchChange&&b.watchChange()})}],link:function(b,c,d,e){e&&(angular.element(c).on("blur",function(){var d=a("number")(b.ngModel,b.round);c.val(d)}),e.$formatters.unshift(function(c){if(void 0==e.$modelValue||""==e.$modelValue)e.$modelValue=0;return a(d.format)(e.$modelValue,b.round)}),e.$parsers.unshift(function(d){if(void 0==
d||""==d)d="0";d=d.replace(/[^\d|\-+|,+]/g,"");var e=d.replace(/,/g,".");if(0>d.indexOf(",")){var f=a("number")(e);d.indexOf(",")==d.length-1&&(f+=",");c.val(f)}d=Number(e);void 0==d&&(d=0);return STP.round(d,b.round)}))}}}]);accApp.directive("ngData",function(){return{controller:["$scope",function(a){}]}});
accApp.directive("ngSum",function(){return{scope:{ngSum:"@",ngData:"=",ngModel:"="},link:function(a,b,c,d){a.$watch("ngData",function(b){var c=0;b&&angular.forEach(b,function(b){c+=Number(b[a.ngSum])||0});a.ngModel=c},!0)}}});
accApp.directive("ngDatepicker",["$window",function(a){return{restrict:"E",require:"^ngModel",scope:{ngModel:"=",ngChange:"&",ngReadonly:"=?",ngDisabled:"=?"},templateUrl:"templates/sys/ng-datepicker.html",controller:["$scope","$filter",function(b,c){b.$watch("ngModel",function(c,a){c&&!_.isDate(c)&&(b.ngModel=new Date(c));b.ngChange&&c!=a&&b.ngChange()})}],link:function(b,c,a,e){}}}]);
accApp.directive("ngDatetimepicker",["$window",function(a){return{restrict:"E",require:"^ngModel",scope:{ngModel:"=",ngChange:"&"},template:'<input type="datetime-local" class="form-control" ng-model="ngModel">',controller:["$scope","$filter",function(b,c){b.$watch("ngModel",function(c,a){var d=c;d&&!_.isDate(d)&&(d=new Date(d));d&&(d.setMilliseconds(0),d.setSeconds(0),b.ngModel=d);b.ngChange&&c!=a&&b.ngChange()})}],link:function(b,c,a,e){}}}]);
accApp.directive("ngRequiredCn",["dmtk",function(a){var b=!1,c=function(c,a){1!=b||a.$viewValue&&""!=a.$viewValue?a.$setValidity("ngRequiredCn",!0):a.$setValidity("ngRequiredCn",!1)};return{restrict:"A",require:"?ngModel",link:function(d,e,f,g){d.$watch(f.ngRequiredCn,function(e){e?d.tks?(b=0<_.filter(d.tks,function(b){return b.tk==e&&b.tk_cn}).length,c(d,g)):a.list(id_app,{tk:e,tk_cn:!0},"tk_cn").then(function(a){b=0==a.data.length?!1:!0;c(d,g)}):(b=!1,c(d,g))});d.$watch(f.ngModel,function(b){c(d,
g)})}}}]);accApp.directive("ngRequiredQ",[function(){return{restrict:"A",require:"?ngModel",link:function(a,b,c,d){a.$watch(c.ngRequiredQ,function(b){b?d.$setValidity("ngRequired",!1):d.$setValidity("ngRequired",!0)})}}}]);
accApp.directive("topMenu",[function(){return{restrict:"E",templateUrl:"templates/sys/top-menu.html",controller:["$scope","$rootScope","colleague","$window","user","app","$location","$http","appInfo","$timeout",function(a,b,c,d,e,f,g,k,h,l){b.notifies_count=0;b.messages_count=0;b.task_count=0;b.getMessages=function(c){b.msgs=[{content:"\u0110ang l\u1ea5y d\u1eef li\u1ec7u..."}];e.getMessagesColleagues(function(a,d){a?(b.messages_count=0,b.msgs=[{content:"Kh\u00f4ng th\u1ec3 l\u1ea5y d\u1eef li\u1ec7u t\u1eeb server"}]):
(b.msgs=d,b.messages_count=d.length,c&&c(d))})};b.getInvitations=function(c){b.notifies={notifications:[{content:"\u0110ang l\u1ea5y d\u1eef li\u1ec7u..."}]};e.getNotifies(function(a,d){a?(b.notifies_count=0,b.notifies={notifications:[{content:"Kh\u00f4ng th\u1ec3 l\u1ea5y d\u1eef li\u1ec7u t\u1eeb server"}]}):(b.notifies=d,b.notifies_count=d.colls.length+d.apps.length+d.notifications.length,c&&c(d))})};b.getTask=function(){b.tasks=[{ten_cv:"\u0110ang l\u1ea5y d\u1eef li\u1ec7u..."}];k.get(server_url+
"/api/"+id_app+"/task?fields=ten_cv,percent,progress,priority&q="+JSON.stringify({progress:{$ne:2},start_date:{$lt:new Date},status:!0,phu_trach:b.user.email})).then(function(c){c=c.data;b.tasks=c;b.task_count=c.length},function(c){b.tasks=[{ten_cv:"Kh\u00f4ng th\u1ec3 l\u1ea5y d\u1eef li\u1ec7u t\u1eeb server"}]})};b.acceptInvitor=function(a,e){"colleague"==a&&c.active(e).then(function(b){0!=g.url().indexOf("/colleague")&&0!=g.url().indexOf("colleague")||d.location.reload()},function(c){b.alert("Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n thao t\u00e1c n\u00e0y")});
"app"==a&&f.active(e).then(function(b){0!=g.url().indexOf("/app")&&0!=g.url().indexOf("app")||d.location.reload()},function(c){b.alert("Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n thao t\u00e1c n\u00e0y")})};b.notAcceptInvitor=function(a,e){"colleague"==a&&c.notaccept(e).then(function(b){0!=g.url().indexOf("/colleague")&&0!=g.url().indexOf("colleague")||d.location.reload()},function(c){b.alert("Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n thao t\u00e1c n\u00e0y")});"app"==a&&f.notaccept(e).then(function(b){0!=
g.url().indexOf("/app")&&0!=g.url().indexOf("app")||d.location.reload()},function(c){b.alert("Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n thao t\u00e1c n\u00e0y")})};b.$watch("app_info",function(c,a){c&&b.getTask()},!0)}]}}]);accApp.directive("horizantalMenu",[function(){return{restrict:"E",templateUrl:"templates/sys/horizantal-menu.html"}}]);accApp.directive("applicationFooter",[function(){return{restrict:"E",templateUrl:"templates/sys/application-footer.html"}}]);
accApp.directive("applicationHeader",[function(){return{restrict:"E",templateUrl:"templates/sys/application-header.html"}}]);accApp.directive("appHeader",[function(){return{restrict:"E",templateUrl:"templates/sys/app-header.html",controller:["$scope","$uibModal","appInfo","$localStorage",function(a,b,c,d){a.confdashboard=function(b){c.info("/dashboard",function(b,a,d){b||c.confDashboard(d)})}}]}}]);accApp.directive("ngPage",[function(){return{restrict:"E",templateUrl:"templates/sys/ng-page.html"}}]);
accApp.directive("ngPageFx",[function(){return{restrict:"E",scope:{service:"=",list:"=",condition:"=",start:"=",pageChanged:"&"},templateUrl:"templates/sys/ng-page.html",controller:["$scope","$http","$rootScope",function(a,b,c){a.current_page=1;a.getPages=function(){a.service.load(id_app,{condition:a.condition,count:1}).then(function(b){b=b.data;a.total_page=STP.round(b.rows_number/a.limit,0);a.total_page<b.rows_number/a.limit&&(a.total_page+=1);0==a.total_page&&(a.total_page=1);a.pages=[];for(b=
1;b<=a.total_page;b++)a.pages.push(b)})};a.goToPage=function(d){d||(d=1);c.nextTick(function(){a.$emit("$dataChangeStart");a.service.load(id_app,{condition:a.condition,page:d,limit:a.limit,fields:a.fields}).then(function(c){var e=c.data;async.map(e,function(c,d){a.emailCurrentUser?b.get(server_url+"/api/follow?q={id_object:'"+c._id+"',user_created:'"+a.emailCurrentUser+"'}").then(function(b){(b=b.data)&&0<b.length?(c.followObject=b[0],c.follow_yn=1):c.follow_yn=0;d()},function(b){c.follow_yn=0;d(b)}):
d()},function(b,c){b&&console.log(b);a.$emit("$dataChangeSuccess");a.current_page=d;a.pageChanged({$page:d});a.list=e})},function(b){a.$emit("$dataChangeError")})})}}],link:function(a,b,c,d){a.total_page=1;a.pages=[1];c.hasOwnProperty("emailCurrentUser")&&(a.emailCurrentUser=c.emailCurrentUser);c.hasOwnProperty("fields")?a.fields=c.fields:a.fields="";c.hasOwnProperty("limit")&&(a.limit=c.limit);c.hasOwnProperty("currentPage")?a.current_page=Number(c.currentPage):a.current_page=1;a.limit||(a.limit=
20);a.$watch("start",function(b){b&&(a.getPages(),a.goToPage(a.current_page),a.start=null)})}}}]);
accApp.directive("list",["$location",function(a){return{restrict:"E",transclude:{title:"?listTitle",extToolbar:"?listExtToolbar",extFilter:"?listExtFilter",body:"listBody",footer:"?listFooter"},templateUrl:"templates/sys/list.html",link:function(b,c,a,e){b.toolbar_show=!0;a.hasOwnProperty("toolbarShow")&&(b.toolbar_show=a.toolbarShow);b.advSearch_show=a.advSearch;a.hasOwnProperty("boxSearch")?("false"==a.boxSearch&&(a.boxSearch=!1),"true"==a.boxSearch&&(a.boxSearch=!0),b.boxSearch=a.boxSearch):b.boxSearch=
!0;a.hasOwnProperty("btnadd")?(e=eval("({"+a.btnadd+"})"),void 0==e.show&&(e.show=!0),void 0==e.text&&(e.text="M\u1edbi"),b.add_show=e.show,b.add_text=e.text):(b.add_show=!0,b.add_text="M\u1edbi");a.btndelete?(e=eval("({"+a.btndelete+"})"),void 0==e.show&&(e.show=!0),void 0==e.text&&(e.text="X\u00f3a"),b.delete_show=e.show,b.delete_text=e.text):(b.delete_text="X\u00f3a",b.delete_show=!0);b.import_show=!0;a.btnimport&&(!1===eval("({"+a.btnimport+"})").show&&(b.import_show=!1),b.import_text="Nh\u1eadp t\u1eeb Excel");
a.btnexport&&eval("({"+a.btnexport+"})").show&&(b.export_show=!0);a.options&&(a=eval("({"+a.options+"})"),b.options_show=!0,b.options_text=a.text);b.showExtraToolbar=!0;c=$(c).find(".extra-button");b.showExtraToolbar=0<c.length&&c[0]?0<c[0].innerText.length:!1}}}]);
accApp.directive("voucher",["$location",function(a){return{restrict:"E",transclude:{title:"?voucherTitle",extToolbar:"?voucherExtToolbar",extFilter:"?voucherExtFilter",body:"?voucherBody",bodyMaster:"?voucherBodyMaster",bodyDetail:"?voucherBodyDetail",footer:"?voucherFooter"},templateUrl:function(b,c){return c.masterDetail?"templates/sys/voucher-master-detail.html":"templates/sys/voucher.html"},link:function(b,c,a,e){b.manTabs={activeTab:0};a.hasOwnProperty("boxSearch")?("false"==a.boxSearch&&(a.boxSearch=
!1),"true"==a.boxSearch&&(a.boxSearch=!0),b.boxSearch=a.boxSearch):b.boxSearch=!0;a.hasOwnProperty("btnadd")?(e=eval("({"+a.btnadd+"})"),void 0==e.show&&(e.show=!0),void 0==e.text&&(e.text="M\u1edbi"),b.add_show=e.show,b.add_text=e.text):(b.add_show=!0,b.add_text="M\u1edbi");a.btndelete?(e=eval("({"+a.btndelete+"})"),void 0==e.show&&(e.show=!0),void 0==e.text&&(e.text="X\u00f3a"),b.delete_show=e.show,b.delete_text=e.text):(b.delete_text="X\u00f3a",b.delete_show=!0);b.import_show=!0;a.btnimport&&(!1===
eval("({"+a.btnimport+"})").show&&(b.import_show=!1),b.import_text="Nh\u1eadp t\u1eeb Excel");a.btnexport&&eval("({"+a.btnexport+"})").show&&(b.export_show=!0);a.options&&(a=eval("({"+a.options+"})"),b.options_show=!0,b.options_text=a.text);b.showExtraToolbar=!0;c=$(c).find(".extra-button");b.showExtraToolbar=0<c.length&&c[0]?0<c[0].innerText.length:!1}}}]);
accApp.directive("stplistheader",["$location",function(a){return{restrict:"E",transclude:!0,templateUrl:"templates/sys/list-header.html",link:function(b,a,d,e){d.hasOwnProperty("boxSearch")?("false"==d.boxSearch&&(d.boxSearch=!1),"true"==d.boxSearch&&(d.boxSearch=!0),b.boxSearch=d.boxSearch):b.boxSearch=!0;d.hasOwnProperty("btnadd")?(a=eval("({"+d.btnadd+"})"),void 0==a.show&&(a.show=!0),void 0==a.text&&(a.text="M\u1edbi"),b.add_show=a.show,b.add_text=a.text):(b.add_show=!0,b.add_text="M\u1edbi");
d.btndelete?(a=eval("({"+d.btndelete+"})"),void 0==a.show&&(a.show=!0),void 0==a.text&&(a.text="X\u00f3a"),b.delete_show=a.show,b.delete_text=a.text):(b.delete_text="X\u00f3a",b.delete_show=!0);d.btn1&&(a=eval("({"+d.btn1+"})"),b.btn1_show=!0,b.btn1_text=a.text,b.btn1_title=a.title,_.isFunction(a.click)&&(b.btn1_click=a.click));d.btn2&&(a=eval("({"+d.btn2+"})"),b.btn2_show=!0,b.btn2_text=a.text,b.btn2_title=a.title,_.isFunction(a.click)&&(b.btn2_click=a.click));d.btn3&&(a=eval("({"+d.btn3+"})"),b.btn3_show=
!0,b.btn3_text=a.text,b.btn3_title=a.title,_.isFunction(a.click)&&(b.btn3_click=a.click));d.btn4&&(a=eval("({"+d.btn4+"})"),b.btn4_show=!0,b.btn4_text=a.text,b.btn4_title=a.title,_.isFunction(a.click)&&(b.btn4_click=a.click));d.btn5&&(a=eval("({"+d.btn5+"})"),b.btn5_show=!0,b.btn5_text=a.text,b.btn5_title=a.title,_.isFunction(a.click)&&(b.btn5_click=a.click));b.import_show=!0;d.btnimport&&(!1===eval("({"+d.btnimport+"})").show&&(b.import_show=!1),b.import_text="Nh\u1eadp t\u1eeb Excel");d.btnexport&&
eval("({"+d.btnexport+"})").show&&(b.export_show=!0)}}}]);accApp.directive("listViewHeader",["$location",function(a){return{restrict:"E",transclude:!0,templateUrl:"templates/sys/list-view-header.html",controller:["$scope","$rootScope",function(b,a){b.$watch("data",function(c){c&&(b.title_view=c[b.headerTitleField],a.title_view=b.title_view)},!0)}],link:function(b,a,d,e){b.headerTitleField=d.headerTitle}}}]);
accApp.directive("stpvoucherheader",function(){return{restrict:"E",transclude:!0,templateUrl:"templates/sys/voucher-header.html",link:function(a,b,c,d){c.btn1&&(b=eval("({"+c.btn1+"})"),a.btn1_show=!0,a.btn1_text=b.text,a.btn1_title=b.title,_.isFunction(b.click)&&(a.btn1_click=b.click));c.btn2&&(b=eval("({"+c.btn2+"})"),a.btn2_show=!0,a.btn2_text=b.text,a.btn2_title=b.title,_.isFunction(b.click)&&(a.btn2_click=b.click));c.btn3&&(b=eval("({"+c.btn3+"})"),a.btn3_show=!0,a.btn3_text=b.text,a.btn3_title=
b.title,_.isFunction(b.click)&&(a.btn3_click=b.click));c.btn4&&(b=eval("({"+c.btn4+"})"),a.btn4_show=!0,a.btn4_text=b.text,a.btn4_title=b.title,_.isFunction(b.click)&&(a.btn4_click=b.click));c.btn5&&(b=eval("({"+c.btn5+"})"),a.btn5_show=!0,a.btn5_text=b.text,a.btn5_title=b.title,_.isFunction(b.click)&&(a.btn5_click=b.click));a.import_show=!0;c.btnimport&&(!1===eval("({"+c.btnimport+"})").show&&(a.import_show=!1),a.import_text="Nh\u1eadp t\u1eeb Excel");c.options&&(c=eval("({"+c.options+"})"),a.options_show=
!0,a.options_text=c.text)}}});accApp.directive("headerFormInputFull",function(){return{restrict:"E",transclude:!0,templateUrl:"templates/sys/header-form-input-full.html",link:function(a,b,c){c.saveText&&(a.save_text=c.saveText);c.cancelText&&(a.cancel_text=c.cancelText);a.windowHeight=window.innerHeight}}});
accApp.directive("formInput",function(){return{restrict:"E",transclude:{title:"?formInputTitle",body:"formInputBody",footer:"?formInputFooter"},templateUrl:function(a,b){return"templates/sys/form-input.html"},link:function(a,b,c){a.save_text=c.saveText?c.saveText:a.getLabel("luu","L\u01b0u").text;a.cancel_text=c.cancelText?c.cancelText:a.getLabel("huu","Hu\u1ef7").text;a.delete_text=c.deleteText?c.deleteText:a.getLabel("xoa","Xo\u00e1").text;a.print_text=c.printText?c.printText:a.getLabel("in","In").text;
a.autoHeight=c.autoHeight&&"true"===c.autoHeight&&568<window.innerHeight;b.bind("keydown",function(b){var c=b.keyCode||b.which;b.ctrlKey&&a.create&&a.form&&!a.form.$invalid&&(83==c?(a.create(),b.preventDefault()):80==c&&(a.create(1),b.preventDefault()))})}}});
accApp.directive("formDetail",function(){return{restrict:"E",transclude:{title:"?formDetailTitle",toolbar:"?formDetailToolbar",body:"formDetailBody",footer:"?formDetailFooter"},templateUrl:"templates/sys/form-detail.html",link:function(a,b,c){a.autoHeight=(!c.autoHeight||"true"===c.autoHeight)&&568<window.innerHeight;b.bind("keydown",function(b){var c=b.keyCode||b.which;b.ctrlKey&&83==c&&a.updateDetail&&a.formdetail&&!a.formdetail.$invalid&&(a.updateDetail(),b.preventDefault())})}}});
accApp.directive("headerFormInput",function(){return{restrict:"E",transclude:!0,templateUrl:"templates/sys/header-form-input.html",link:function(a,b,c){c.saveText&&(a.save_text=c.saveText);c.cancelText&&(a.cancel_text=c.cancelText)}}});
accApp.directive("headerDialogSelect",function(){return{restrict:"E",templateUrl:"templates/sys/header-dialog-select.html",controller:["$rootScope","$scope","appInfo","$http",function(a,b,c,d){}],link:function(a,b,c){c.hasOwnProperty("title")?a.title=c.title:a.title="Danh s\u00e1ch";c.hasOwnProperty("placeholder")?a.placeholder=c.placeholder:a.placeholder="G\u00f5 t\u1eeb c\u1ea7n t\u00ecm..."}}});
accApp.directive("footerFormInput",function(){return{restrict:"E",transclude:!0,templateUrl:"templates/sys/footer-form-input.html",link:function(a,b,c){c.saveText&&(a.save_text=c.saveText);c.cancelText&&(a.cancel_text=c.cancelText)}}});
accApp.directive("rptHeader",["$location",function(a){return{restrict:"E",transclude:!0,templateUrl:"templates/sys/rpt-header.html",controller:["$uibModal","$scope","$rootScope",function(b,a,d){a.openKbm=function(){if(!a.kbm)return d.alert("Miss attr kbm");d.openUrl(a.kbm)};a.hideCondition=function(b){a.condition_show=b?!1:!a.condition_show;angular.element(document.getElementById("rptContent")).controller("scrollableContent").scrollTo(0)}}],link:function(b,a,d,e){d.kbm&&(b.kbm=d.kbm,b.kbm_yn=!0);
b.btnok_text="Xem";b.btnok_show=!0;d.btnok&&(a=eval("({"+d.btnok+"})"),a.text&&(b.btnok_text=a.text),a.show&&(b.btnok_show=a.show));d.btn1&&(a=eval("({"+d.btn1+"})"),b.btn1_show=!0,b.btn1_text=a.text,b.btn1_title=a.title,_.isFunction(a.click)&&(b.btn1_click=a.click));d.btn2&&(a=eval("({"+d.btn2+"})"),b.btn2_show=!0,b.btn2_text=a.text,b.btn2_title=a.title,_.isFunction(a.click)&&(b.btn2_click=a.click));d.btn3&&(a=eval("({"+d.btn3+"})"),b.btn3_show=!0,b.btn3_text=a.text,b.btn3_title=a.title,_.isFunction(a.click)&&
(b.btn3_click=a.click));d.btn4&&(a=eval("({"+d.btn4+"})"),b.btn4_show=!0,b.btn4_text=a.text,b.btn4_title=a.title,_.isFunction(a.click)&&(b.btn4_click=a.click));d.btn5&&(a=eval("({"+d.btn5+"})"),b.btn5_show=!0,b.btn5_text=a.text,b.btn5_title=a.title,_.isFunction(a.click)&&(b.btn5_click=a.click));d.btnprint?(a=eval("({"+d.btnprint+"})"),void 0==a.show&&(a.show=!0),b.btnprint_show=a.show):b.btnprint_show=!0;d.btnexcel?(d=eval("({"+d.btnexcel+"})"),void 0==d.show&&(d.show=!0),b.btnexcel_show=d.show):
b.btnexcel_show=!0}}}]);
accApp.directive("report",["$location",function(a){return{restrict:"E",transclude:{filter:"reportFilter",viewer:"reportViewer"},templateUrl:"templates/sys/report.html",controller:["$uibModal","$scope","$rootScope",function(a,c,d){c.openKbm=function(){if(!c.kbm)return d.alert("Miss attr kbm");d.openUrl(c.kbm)};c.hideCondition=function(a){c.condition_show=a?!1:!c.condition_show;angular.element(document.getElementById("rptContent")).controller("scrollableContent").scrollTo(0)}}],link:function(a,c,d,
e){d.kbm&&(a.kbm=d.kbm,a.kbm_yn=!0);a.btnok_text="Xem";a.btnok_show=!0;d.btnok&&(c=eval("({"+d.btnok+"})"),c.text&&(a.btnok_text=c.text),c.show&&(a.btnok_show=c.show));d.btn1&&(c=eval("({"+d.btn1+"})"),a.btn1_show=!0,a.btn1_text=c.text,a.btn1_title=c.title,_.isFunction(c.click)&&(a.btn1_click=c.click));d.btn2&&(c=eval("({"+d.btn2+"})"),a.btn2_show=!0,a.btn2_text=c.text,a.btn2_title=c.title,_.isFunction(c.click)&&(a.btn2_click=c.click));d.btn3&&(c=eval("({"+d.btn3+"})"),a.btn3_show=!0,a.btn3_text=
c.text,a.btn3_title=c.title,_.isFunction(c.click)&&(a.btn3_click=c.click));d.btn4&&(c=eval("({"+d.btn4+"})"),a.btn4_show=!0,a.btn4_text=c.text,a.btn4_title=c.title,_.isFunction(c.click)&&(a.btn4_click=c.click));d.btn5&&(c=eval("({"+d.btn5+"})"),a.btn5_show=!0,a.btn5_text=c.text,a.btn5_title=c.title,_.isFunction(c.click)&&(a.btn5_click=c.click));d.btnprint?(c=eval("({"+d.btnprint+"})"),void 0==c.show&&(c.show=!0),a.btnprint_show=c.show):a.btnprint_show=!0;d.btnexcel?(d=eval("({"+d.btnexcel+"})"),void 0==
d.show&&(d.show=!0),a.btnexcel_show=d.show):a.btnexcel_show=!0}}}]);accApp.directive("navbarPrint",function(){return{restrict:"E",templateUrl:"templates/sys/navbar-print.html"}});accApp.factory("$cache_lists",function(){return{}});
accApp.directive("stpLink",function(){return{restrict:"E",scope:{link:"=",collection:"@",collectionsLink:"@"},templateUrl:"templates/sys/link.html",controller:["$scope","$shttp","$window","$location","$rootScope","appInfo","link",function(a,b,c,d,e,f,g){initLabel(e,a,f,"LINK",b);a.textSearch="";a.location=d.url();c=eval("({"+a.collectionsLink+"})");var k=_.keys(c),h={};k.forEach(function(a){var b=eval("("+(a+"Module")+")");h[a]=b.title});a.collectionsTitleString=_.values(h).join();a.load=function(){var c=
server_url+"/api/"+id_app+"/linkslist?_id="+a.link._id+"&collections="+k.join();b.get(c,{cache:!0}).then(function(b){a.link.links=b.data},function(a){a.data&&console.log(a.data)})};a.getHeaderCollection=function(a){return h[a.collection_obj]};a.search=function(c){return b.get(server_url+"/api/"+id_app+"/search?collections="+a.collectionsLink+"&value="+c,{cache:!0}).then(function(a){return a.data})};a.addLink=function(b){a.textSearch="";if(!_.find(a.link.links,function(a){return a.obj._id==b._id})){var c=
{};c.id_a=a.link._id;c.collection_a=a.collection;c.collection_b=b.collection_name;c.collection_obj=b.collection_name;c.id_b=b._id;g.create(id_app,c).then(function(d){_.extend(c,d.data);c.obj=b;c.title=b.title;a.link.links.push(c)},function(a){a.data&&e.alert(a.data)})}};a.unLink=function(b){g.delete(id_app,b._id).then(function(c){a.link.links=_.reject(a.link.links,function(a){return a._id==b._id})},function(a){a.data&&e.alert(a.data)})};a.getItem=function(b,c,d){a.addLink(b,d)}}],link:function(a,
b,c,d){c.link&&c.collection&&c.collectionsLink||console.error("stp-link directive require attributes:link,collection,collection-link");a.$watch("link",function(b){b&&(a.link.links||(a.link.links=[]),a.load())})}}});
accApp.directive("getValue",["$http","$rootScope",function(a,b){return{restrict:"A",scope:{module:"@",field:"@",condition:"@"},link:function(b,d,e){(function(c,e){if(b.module){"dmkh"===b.module&&(b.module="customer");"dmtk"===b.module&&(b.module="account");var f=server_url+"/api/"+id_app+"/"+b.module+"?t=1";if(c)try{c=JSON.parse("{"+c+"}"),f=f+"&q="+JSON.stringify(c)}catch(h){console.log(h.message,"{"+c+"}"),f=f+"&"+c}e&&(f=f+"&fields="+e);a.get(f).then(function(a){var b;a.data&&0<a.data.length&&
(b=a.data[0][e]);b||(b="");d.text(b)},function(a){d.text(a.data)})}})(b.condition,b.field)}}}]);
accApp.directive("ngGetInfo",["$http",function(a){return{restrict:"A",scope:{conditionValue:"=",runWhenConditionChanged:"=",ngModel:"="},controller:["$scope",function(b){var c=function(c,e,f){c=server_url+"/api/"+c+"/"+b.pathService+"?t=1";e&&(angular.isObject(e)?(e=JSON.stringify(e),c=c+"&q="+e):c=c+"&"+e);f&&(c=c+"&fields="+f);return a.get(c)};b.getValue=function(a){var d={},f;for(f in b.condition){var g=b.condition[f];d[f]="???"==g?b.conditionValue:g}c(id_app,d,b.fieldInfo).then(function(c){c=
c.data;1==c.length&&a(c[0][b.fieldInfo])})}}],link:function(a,c,d){c=eval("({"+d.ngGetInfo+"})");a.fieldInfo=c.fieldInfo;var b=eval("("+c.module+"Module)");a.pathService=b.server_path;a.condition=c.condition;d.hasOwnProperty("runWhenConditionChanged")||(a.runWhenConditionChanged=!0);a.$watch("conditionValue",function(b,c){a.runWhenConditionChanged&&(b||b===c?a.fieldInfo&&a.getValue(function(b){b&&(a.ngModel=b)}):a.ngModel=null)})}}}]);
accApp.directive("history",function(){return{restrict:"E",scope:{link:"=",module:"@",actions:"@"},templateUrl:"templates/sys/history.html",controller:["$scope","$http","$uibModal","$rootScope","appInfo",function(a,b,c,d,e){initLabel(d,a,e,"HISTORY",b);var f=eval("("+a.module+"Module)");a.getHistory=function(){var c=f.url_service(server_url)+"/g/history/"+a.link._id;a.actions&&(c=c+"?actions="+a.actions);b.get(c).then(function(b){b=b.data;b.forEach(function(a){a.action_text="GET"==a.action?"\u0110\u00e3 xem":
"UPDATE"==a.action?"\u0110\u00e3 c\u1eadp nh\u1eadt":"ADD"==a.action?"\u0110\u00e3 t\u1ea1o":a.action});a.history=b},function(a){console.error(a)})};a.openProfile=function(a){viewProfile(c,a)}}],link:function(a,b,c,d){a.$watch("link",function(b){b&&a.getHistory()})}}});accApp.directive("parseHtml",function(){return{restrict:"A",scope:{parseHtml:"="},link:function(a,b,c,d){a.$watch("parseHtml",function(a,c){a&&_.isString(a)&&(/<[a-z][\s\S]*>/i.test(a)?b.html(a):b.html(a.replace(/\n/g,"<br/>")))})}}});
accApp.directive("parseText",function(){return{restrict:"A",scope:{parseText:"=",limit:"@"},link:function(a,b,c,d,e){a.$watch("parseText",function(c,d){c&&(/<[a-z][\s\S]*>/i.test(c)&&(b.html(c),c=b.text()),a.limit&&c.length>Number(a.limit)&&(b.attr("title",c),c=c.substring(0,a.limit)+"..."),b.text(c))})}}});
accApp.directive("textcomplete",["Textcomplete",function(a){return{restrict:"EA",scope:{members:"=",message:"="},template:"<textarea class=\"form-control\" rows=\"5\" ng-model='message' type='text'></textarea>",link:function(b,c,d){b.$watch("members",function(d){if(d&&0<d.length){var e=b.members;d=c.find("textarea");d=new a(d,[{match:/(^|\s)@(\w*)$/,search:function(a,b){b($.map(e,function(b){return 0===b.toLowerCase().indexOf(a.toLowerCase())?b:null}))},index:2,replace:function(a){return"$1@"+a+" "}}]);
$(d).on({"textComplete:select":function(a,c){b.$apply(function(){b.message=c})},"textComplete:show":function(a){$(this).data("autocompleting",!0)},"textComplete:hide":function(a){$(this).data("autocompleting",!1)}})}})}}}]);accApp.directive("routeLoader",function(){return{restrict:"EA",link:function(a,b){function c(){b.css("display","none")}var d=b.css("display");a.$on("$routeChangeStart",function(){b.css("display",d)});a.$on("$routeChangeSuccess",c);a.$on("$routeChangeError",c);c()}}});
accApp.directive("serverLoader",function(){return{restrict:"EA",link:function(a,b){function c(){b.css("display","none")}var d=b.css("display");a.$on("$dataChangeStart",function(){a.serverAction="\u0110ang t\u1ea3i d\u1eef li\u1ec7u";b.css("display",d)});a.$on("$dataSaveStart",function(){a.serverAction="\u0110ang l\u01b0u d\u1eef li\u1ec7u";b.css("display",d)});a.$on("$dataChangeSuccess",c);a.$on("$dataChangeError",c);a.$on("$dataSaveSuccess",c);a.$on("$dataSaveError",c);c()}}});
accApp.directive("fileUploadProgress",function(){return{restrict:"EA",link:function(a,b){function c(){b.css("display","none")}var d=b.css("display");a.$on("$fileUploadStart",function(){a.serverAction="\u0110ang t\u1ea3i d\u1eef li\u1ec7u";b.css("display",d)});a.$on("$fileUploadSuccess",c);a.$on("$fileUploadError",c);c()}}});
accApp.directive("follow",function(){return{restrict:"E",scope:{collectionsFollow:"@"},templateUrl:"templates/sys/follow.html",controller:["$scope","$rootScope","$http","appInfo",function(a,b,c,d){initLabel(b,a,d,"FOLLOW",c);a.load=function(){d.info("follow",function(b,d,g){a.follows=[];!b&&g._id&&a.collectionsFollow&&g&&c.get(server_url+"/api/"+g._id+"/follow?q={user_created:'"+d.email+"'}&collections="+a.collectionsFollow).then(function(b){a.follows=b.data})})}}],link:function(a,b,c,d){a.load()}}});
accApp.directive("like",function(){return{restrict:"E",templateUrl:"templates/sys/like.html",controller:["$scope","$rootScope","$http","appInfo",function(a,b,c,d){a.load=function(){d.info("like_module",function(b,d,g){a.likes=[];!b&&g._id&&c.get(server_url+"/api/"+g._id+"/like_module?q={user_created:'"+d.email+"',like:true}").then(function(b){a.likes=b.data})})}}],link:function(a,b,c,d){a.load()}}});
accApp.directive("shortcut",["$document","$rootScope",function(a,b){return{restrict:"A",link:function(c,d,e){a.bind("keydown",function(a){(a.ctrlKey&&(65==a.which||77==a.which||114==a.which||78==a.which||68==a.which||69==a.which||80==a.which||85==a.which||83==a.which)||116==a.which)&&a.preventDefault();b.$apply(function(){b.$broadcast("keydown",a)})});document.addEventListener("backbutton",function(a){if(b.ui_dropdowns)for(var c in b.ui_dropdowns)b.Ui.turnOff(c);b.$apply(function(){b.$broadcast("backbutton",
"1")});a.preventDefault()},!1)}}}]);accApp.directive("input",function(){return{restrict:"E",priority:-1,link:function(a,b,c){"date"==c.type&&$(b).updatePolyfill()}}});
accApp.directive("nextFocus",function(){return{restrict:"A",link:function(a,b,c){function d(){var a=angular.element(b[0].querySelector(".always-focus"));a&&a.focus()}var e=angular.element(b[0].querySelectorAll("input,textarea"));if(0<e.length)for(a=0;a<e.length;a++)e.eq(a).bind("blur",function(a){d()});b.bind("click",function(a){"TEXTAREA"!==document.activeElement.nodeName.toUpperCase()&&"INPUT"!==document.activeElement.nodeName.toUpperCase()&&"SELECT"!==document.activeElement.nodeName.toUpperCase()&&
d()});b.bind("keydown",function(a){if(13===(a.keyCode||a.which)){if(0<angular.element(b[0].querySelectorAll(".always-focus")).length)return d();if("TEXTAREA"!==document.activeElement.nodeName.toUpperCase()&&0>document.activeElement.className.indexOf("always-focus")&&(e=angular.element(b[0].querySelectorAll(".form-control,input,textarea")),0<e.length)){for(var c=e.index(document.activeElement)+1;;){if(c>=e.length){c=0;break}if(!e.eq(c).is(":disabled")&&!e.eq(c).is(":hidden"))break;c+=1}e.eq(c).focus();
a.preventDefault()}}})}}});accApp.directive("a",function(){return{restrict:"E",link:function(a,b,c){b.bind("click",function(){c.href&&c.href.indexOf("javascript")})}}});
accApp.directive("barcode",function(){return{restrict:"E",scope:{data:"=",fieldCode:"@",fieldLabel:"@",fieldPrice:"@",fieldQty:"@",onClick:"&?",onClose:"&?"},templateUrl:"templates/sys/barcode.html",controller:["$scope","$uibModal","$rootScope",function(a,b,c){a.server_url=server_url_report;a.STP=c.STP;a.barcode_options={format:"CODE128",lineColor:"#000000",width:1,height:50,columns:"four",displayValue:!0,displayLabel:!0,displayPrice:!0,fontOptions:"",font:"monospace",textAlign:"center",textPosition:"bottom",
textMargin:2,fontSize:20,background:"#ffffff",margin:0,marginTop:void 0,marginBottom:void 0,marginLeft:void 0,marginRight:void 0,valid:function(a){}};a.click=function(b){if(a.onClick)a.onClick({$item:b})};a.barcodeOptionsShow=function(){b.open({templateUrl:"templates/sys/barcode-options.html",controller:["$scope","$rootScope","$controller","$http","$uibModalInstance","parentScope","appInfo",function(a,b,c,g,k,h,l){initLabel(b,a,l,"SYS",g);a.barcode_options=h.barcode_options;a.cancel=function(){k.close()}}],
size:"md",resolve:{parentScope:function(){return a}}})};a.printBarcode=function(a){a||(a="");var b=document.getElementById("printViewBarcode");if(!b)return c.alert("M\u1eabu in thi\u1ebfu id 'printViewBarcode'");c.printS(b.innerHTML,a)};a.$watch("data",function(b,c){if(b){a._data=[];var d,e;a.data.forEach(function(b){void 0==b[a.fieldQty]&&(b[a.fieldQty]=1);for(d=0;d<b[a.fieldQty];d++)e={},_.extend(e,b),delete e.$$hashKey,a._data.push(e)})}},!0)}],link:function(a,b,c){a.fieldQty||(a.fieldQty="so_luong")}}});
accApp.directive("buttonSlide",["$location",function(a){return{restrict:"E",scope:{width:"@",height:"@",actions:"=?",text:"@",top:"@"},transclude:{title:"?btnTitle",content:"?btnContent"},templateUrl:"templates/sys/button-slide.html",link:function(a,c,d,e){a.width=a.width?Number(a.width):250;a.height=a.heigh?Number(a.height):window.innerHeight-200;a.is_close=!0;a.showhide=function(){a.is_close=!a.is_close};a.hide=function(){a.is_close=!0};a.show=function(){a.is_close=!1};a.actions={};a.actions.hide=
a.hide;a.actions.showhide=a.showhide;a.top=a.top?Number(a.top):120}}}]);var isDrapItem=!1;
