var loginModule=angular.module("loginModule",["ngRoute"]);
loginModule.controller("loginController",["$scope","$rootScope","api","$http","$location","user","Base64","$window","$interval","$localStorage","appInfo",function(a,b,l,d,h,g,k,m,p,n,c){b.function_title=MAIN_APPLICATION_NAME;b.function_code="";a.interfaces=interfaces;a.interface=n.get("interface");initLabel(b,a,c,"login",d);n.set("token","");n.set("id_app","");b.app_info=void 0;b.isLogined=!1;b.messages_count=0;b.notifies_count=0;b.task_count=0;id_app=void 0;b.id_app=void 0;b.user=void 0;l.init();
a.data={};a.auth_google=function(a){a||(a="dashboard");n.set("interface",a);var f=m.open(server_url+"/auth/google","Google authentication"),e=p(function(){try{if(f.location.href&&f.location.href.indexOf("/auth/google/callback")&&f.document.body.innerHTML&&0<=f.document.body.innerHTML.indexOf("access_token")){var c=JSON.parse(f.document.title).access_token;p.cancel(e);f.close();n.set("token",c);l.init(c);g.getInfo(function(f){b._interface=a;b.user=f;h.url("/app")})}}catch(q){console.log(q)}},500)};
a.auth_facebook=function(a){a||(a="dashboard");n.set("interface",a);var f=m.open(server_url+"/auth/facebook","Facebook authentication"),e=p(function(){try{if(f.location.href&&f.location.href.indexOf("/auth/facebook/callback")&&f.document.body.innerHTML&&0<=f.document.body.innerHTML.indexOf("access_token")){var c=f.document.title;p.cancel(e);f.close();n.set("token",c);l.init(c);g.getInfo(function(f){b._interface=a;b.user=f;h.url("/app")})}}catch(q){}},500)};a.auth_local=function(e){e||(e="dashboard");
n.set("interface",e);a.data.username=$("#username").val();a.data.password=$("#password").val();var f=server_url+"/auth/local",c="Basic "+k.encode(a.data.username+":"+a.data.password);a.isLogin=!0;a.$emit("$dataSaveStart");a.messageError="";var m=b.getCacheFactory(null,"SYSTEM"),p=f+c;b.error=void 0;_online?d.get(f,{headers:{Authorization:c}}).then(function(c){a.messageError="";var k=c.data;a.isLogin=!1;a.$emit("$dataSaveSuccess");n.set("token",k);l.init(k);g.getInfo(function(a,c){if(a)return console.log("error login",
a);b._interface=e;b.user=c;m.put(p,{token:k,user:c},function(a,f){a?(console.log("error cache token",a),b.toast("Error cache data login"+a)):console.log("cached token")});f=server_url+"/api/app?access_token="+k;d.get(f).then(function(a){1===a.data.length&&n.set("id_app",a.data[0]._id);b.openDefaultInterface()},function(a){h.url("/app")})})},function(f){a.messageError=f.data?"T\u00ean \u0111\u0103ng nh\u1eadp ho\u1eb7c m\u1eadt kh\u1ea9u kh\u00f4ng ch\u00ednh x\u00e1c":"Ch\u01b0\u01a1ng tr\u00ecnh kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7";
a.isLogin=!1;a.$emit("$dataSaveError")}):(a.isLogin=!1,console.log("login offline"),b.user={email:a.data.username},m.get(p,function(f,c){a.$apply(function(){if(!c||f)delete b.user,console.log("error login offline",f,p),a.messageError="Ch\u01b0\u01a1ng tr\u00ecnh kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7",a.$emit("$dataSaveError");else{a.messageError="";var d=c.token;a.isLogin=!1;a.$emit("$dataSaveSuccess");n.set("token",d);l.init(d);b.user=c.user;b._interface=e;h.url("/app")}})}))};
a.signup=function(){h.url("/signup")}}]);
loginModule.controller("signupController",["$scope","$rootScope","api","$http","$location","$localStorage","appInfo","$routeParams",function(a,b,l,d,h,g,k,m){b.function_title=MAIN_APPLICATION_NAME;b.function_code="";initLabel(b,a,k,"login",d);g.remove("token");g.remove("id_app");id_app=b.app_info=void 0;b.id_app=void 0;b.isLogined=!1;g.remove("endpoint64");delete b.commands;delete b.cmdmodules;b.user=void 0;l.init();b.token=null;b=g.partner;b||(b=m.invb);a.data={partner:b};a.signup=function(){a.messageError=
"";d.post(server_url+"/signup",a.data).then(function(b){b=b.data;a.alertType="alert alert-success";a.messageError=b;a.data={}},function(b){a.alertType="alert alert-danger";a.messageError=b.data})}}]);var notificationShowed={};
loginModule.factory("user",["$http","$shttp","$localStorage","$rootScope","$location","socket","nodeWebkit","$uibModal","Base64",function(a,b,l,d,h,g,k,m,p){return{getInfo:function(a){d.user?a(null,d.user):b.get(server_url+"/api/user",{cache:!0}).then(function(b){var e=b.data;b=e.name.split(" ");e.last_name=b[b.length-1];d.error=void 0;d.user=e;l.setObject("currentuser",e);g.on("connect",function(){g.emit("login",{token:e.token,email:e.email})});g.emit("login",{token:e.token,email:e.email});g.on("notify:count",
function(a){d.notifies_count=a;notificationShowed.so_thong_bao_chua_doc||(notificationShowed.so_thong_bao_chua_doc=1,a&&k.notification("B\u1ea1n c\u00f3 "+a.toString()+" th\u00f4ng b\u00e1o ch\u01b0a \u0111\u1ecdc","","/notification"))});g.on("notify:new",function(a){notificationShowed[a._id+":new"]||(notificationShowed[a._id+":new"]=a,k.notification(a.body,"Th\u00f4ng b\u00e1o t\u1eeb "+a.sender,{sender:a.sender,content:a.content,title:a.title,id:a._id,onClick:function(){notificationModule.quickedit(m,
a._id)}}))});g.on("message:count",function(a){d.messages_count=a;notificationShowed.so_tin_nhan_chua_doc||(notificationShowed.so_tin_nhan_chua_doc=1,a&&k.notification("B\u1ea1n c\u00f3 "+a.toString()+" tin nh\u1eafn ch\u01b0a \u0111\u1ecdc","","/message"))});g.on("message:new",function(a){notificationShowed[a._id+":new"]||(notificationShowed[a._id+":new"]=a,k.notification(a.content,"Tin nh\u1eafn t\u1eeb "+a.sender,"/message/chat/"+a.sender))});g.on("call:in",function(a){notificationShowed[a._id+
":in"]||(notificationShowed[a._id+":in"]=a,dmkhModule.callIn(m,a),a.ten_kh?k.notification(a.ten_kh+" \u0111ang g\u1ecdi...","/dmkh/view/"+a.id_kh):k.notification(a.phone+" \u0111ang g\u1ecdi...","/dmkh/add?dien_thoai="+a.phone))});g.on("pbl:new",function(a){notificationShowed[a._id+":new"]||(notificationShowed[a._id+":new"]=a,a.id_app===id_app&&0==a.trang_thai&&k.notification("Phi\u1ebfu \u0111\u1eb7t ch\u1ed7 m\u1edbi","",{url:"/pbl/edit/"+a._id,onClick:function(){pblModule.quickedit(m,a._id)}}))});
g.on("pbl:update",function(a){notificationShowed[a._id+":update"]||(notificationShowed[a._id+":update"]=a,a.id_app===id_app&&0==a.trang_thai&&k.notification("Phi\u1ebfu \u0111\u1eb7t ch\u1ed7 \u0111\u00e3 \u0111\u01b0\u1ee3c c\u1eadp nh\u1eadt","",{url:"/pbl/edit/"+a._id,onClick:function(){pblModule.quickedit(m,a._id)}}))});g.on("disconnect",function(){});a(null,e)},function(b){b=b.data;var e;b||(e=l.getObject("currentuser"));e?(d.error=void 0,d.user=e,a(null,e)):(d.error=b,d.user=void 0,a(b),h.url("login"))})},
getProfile:function(a,c){if(0<=a.indexOf("guest@")){var e=a.split("@")[1],e=window.atob(e);c(null,{email:a,name:e,picture:"/images/avatar.jpg"})}else e=d.getCacheFactory(null,"SYSTEM"),b.get(server_url+"/api/profile?email="+a,{cache:e}).then(function(a){c(null,a.data)},function(a){c(a.data)})},getProfileByToken:function(a){var c=d.getCacheFactory(null,"SYSTEM");b.get(server_url+"/api/profile",{cache:c}).then(function(b){a(null,b.data)},function(b){a(b.data)})},updateProfile:function(b,c){a.post(server_url+
"/api/updateprofile",b).then(function(a){c(null,a.data)},function(a){c(a.data)})},updatePassword:function(b,c){a.post(server_url+"/api/changepassword",b).then(function(a){c(null,a.data)},function(a){c(a.data)})},resetPassword:function(b,c){a.get(server_url+"/resetpassword?email="+b).then(function(a){c(null,a.data)},function(a){c(a.data)})},getNotifies:function(a){b.get(server_url+"/api/notifies",{cache:!0}).then(function(b){a(null,b.data)},function(b){a(b.data)})},getMessagesColleagues:function(a,
c){b.get(server_url+"/api/message/colleague/latest",{cache:!0}).then(function(b){a(null,b.data)},function(b){a(b.data)})},logout:function(b){if(!l.get("token"))return b;var c=server_url+"/api/user/logout";endpoint&&(c=c+"?ep="+endpoint);a.get(c).then(function(a){b(a.data)},function(a){b()})}}}]);
loginModule.controller("uploadController",["$scope","user","$localStorage","$rootScope","$location","app","$window","$routeParams",function(a,b,l,d,h,g,k,m){b=m.folder;a.action=server_url+"/api/uploadfile?access_token="+l.get("token")+"&folder="+b}]);loginModule.controller("uploadExcelController",["$scope","user","$localStorage","$rootScope","$location","app","$window","$routeParams",function(a,b,l,d,h,g,k,m){a.action=server_url+"/api/uploadexcel?access_token="+l.get("token")}]);
loginModule.controller("profileController",["$scope","user","$localStorage","$rootScope","$location","app","$window","$interval","appInfo","$http",function(a,b,l,d,h,g,k,m,p,n){d.function_title="Th\u00f4ng tin ng\u01b0\u1eddi d\u00f9ng";d.function_code="profile";initLabel(d,a,p,"login",n);p.info("profile",function(c,e,f){if(!c){a.access_token=l.get("token");var g=server_url+"/api/token";b.getProfileByToken(function(b,c){if(b)return a.alertType="danger",a.messageError=b;a.alertType="success";a.data=
c;n.get(g).then(function(b){a.tokens=b.data},function(a){console.log("error when get tokens of user",a.data)})});a.deleteToken=function(b){confirm("B\u1ea1n ch\u1eafc ch\u1eafn mu\u1ed1n x\u00f3a token n\u00e0y?")&&n.delete(g+"/"+b).then(function(c){a.tokens=_.filter(a.tokens,function(a){return a._id!==b})},function(a){d.alert(a.data||"Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7")})};a.updateProfile=function(){a.messageError="";b.updateProfile(a.data,function(b){if(b)return a.alertType=
"danger",a.messageError=b;a.alertType="success";a.messageError="B\u1ea1n \u0111\u00e3 c\u1eadp nh\u1eadt th\u00e0nh c\u00f4ng!"})};a.updatePassword=function(){a.messageError="";b.updatePassword({oldPassword:a.oldPassword,newPassword:a.newPassword,reNewPassword:a.reNewPassword},function(b){if(b)return a.alertTypeChangePass="danger",a.messageErrorChangePass=b;a.alertTypeChangePass="success";a.messageErrorChangePass="B\u1ea1n \u0111\u00e3 thay \u0111\u1ed5i m\u1eadt kh\u1ea9u th\u00e0nh c\u00f4ng!"})}}})}]);
loginModule.controller("resetPasswordController",["$scope","user","$rootScope","$location","app","appInfo","$http",function(a,b,l,d,h,g,k){l.function_title=MAIN_APPLICATION_NAME;l.function_code="";initLabel(l,a,g,"login",k);a.resetPassword=function(){a.messageError="";b.resetPassword(a.email,function(b,d){b?(a.alertType="alert alert-danger",a.messageError=b):(a.alertType="alert alert-success",a.messageError=d)})}}]);
loginModule.controller("logoutController",["$scope","$localStorage","api","$location","$rootScope","user","$window","$timeout","appInfo","$http",function(a,b,l,d,h,g,k,m,p,n){h.function_title=MAIN_APPLICATION_NAME;h.function_code="";initLabel(h,a,p,"login",n);g.logout(function(a){h.token=null;b.remove("token");b.remove("id_app");b.remove("endpoint64");h.app_info=void 0;h.isLogined=!1;id_app=null;h.id_app=void 0;delete h.commands;delete h.cmdmodules;l.init();d.url("/login");if(h.user){var c;"google"==
h.user.server&&(c="https://mail.google.com/mail/u/0/?logout&hl=en");h.user=void 0;if(c){var f=k.open(c,"Logout","height=400,width=400");m(function(){f.close()},3E3)}}})}]);loginModule.controller("downloadController",["$scope","$http",function(a,b){b.get(server_url+"/public/versioninfo").then(function(b){a.downloads=b.data})}]);
loginModule.config(["$routeProvider","$locationProvider",function(a,b){a.when("/signup",{templateUrl:"templates/login/templates/signup.html",controller:"signupController"}).when("/resetpassword",{templateUrl:"templates/login/templates/resetpassword.html",controller:"resetPasswordController"}).when("/profile",{templateUrl:"templates/login/templates/profile.html",controller:"profileController"}).when("/login",{templateUrl:"templates/login/templates/login.html",controller:"loginController"}).when("/logout",
{templateUrl:"templates/login/templates/callback.html",controller:"logoutController"}).when("/download",{templateUrl:"templates/login/templates/download.html",controller:"downloadController"}).when("/uploadfile/:folder",{templateUrl:"templates/login/templates/upload.html",controller:"uploadController"}).when("/uploadexcel",{templateUrl:"templates/login/templates/upload.html",controller:"uploadExcelController"})}]);
