var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var b=0,d={next:function(){if(b<a.length){var f=b++;return{value:c(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in b||(b[f]={});b=b[f]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
for(var languages=["en","vn"],i18n={en:{useLongScale:!1,baseSeparator:"-",unitSeparator:"and ",base:{0:"zero",1:"one",2:"two",3:"three",4:"four",5:"five",6:"six",7:"seven",8:"eight",9:"nine",10:"ten",11:"eleven",12:"twelve",13:"thirteen",14:"fourteen",15:"fifteen",16:"sixteen",17:"seventeen",18:"eighteen",19:"nineteen",20:"twenty",30:"thirty",40:"forty",50:"fifty",60:"sixty",70:"seventy",80:"eighty",90:"ninety"},units:"hundred thousand million billion trillion quadrillion quintillion sextillion septillion octillion nonillion decillion undecillion duodecillion tredecillion quattuordecillion quindecillion".split(" "),
unitExceptions:[]},vn:{useLongScale:!1,baseSeparator:" ",unitSeparator:" ",base:{0:"kh\u00f4ng",1:"m\u1ed9t",2:"hai",3:"ba",4:"b\u1ed1n",5:"n\u0103m",6:"s\u00e1u",7:"b\u1ea3y",8:"t\u00e1m",9:"ch\u00edn",10:"m\u01b0\u1eddi",15:"m\u01b0\u1eddi l\u0103m",20:"hai m\u01b0\u01a1i",21:"hai m\u01b0\u01a1i m\u1ed1t",25:"hai m\u01b0\u01a1i l\u0103m",30:"ba m\u01b0\u01a1i",31:"ba m\u01b0\u01a1i m\u1ed1t",40:"b\u1ed1n m\u01b0\u01a1i",41:"b\u1ed1n m\u01b0\u01a1i m\u1ed1t",45:"b\u1ed1n m\u01b0\u01a1i l\u0103m",
50:"n\u0103m m\u01b0\u01a1i",51:"n\u0103m m\u01b0\u01a1i m\u1ed1t",55:"n\u0103m m\u01b0\u01a1i l\u0103m",60:"s\u00e1u m\u01b0\u01a1i",61:"s\u00e1u m\u01b0\u01a1i m\u1ed1t",65:"s\u00e1u m\u01b0\u01a1i l\u0103m",70:"b\u1ea3y m\u01b0\u01a1i",71:"b\u1ea3y m\u01b0\u01a1i m\u1ed1t",75:"b\u1ea3y m\u01b0\u01a1i l\u0103m",80:"t\u00e1m m\u01b0\u01a1i",81:"t\u00e1m m\u01b0\u01a1i m\u1ed1t",85:"t\u00e1m m\u01b0\u01a1i l\u0103m",90:"ch\u00edn m\u01b0\u01a1i",91:"ch\u00edn m\u01b0\u01a1i m\u1ed1t",95:"ch\u00edn m\u01b0\u01a1i l\u0103m"},
units:["tr\u0103m","ng\u00e0n","tri\u1ec7u","t\u1ef7","ngh\u00ecn t\u1ef7"],unitExceptions:[]}},util={defaults:function(a,c){null==a&&(a={});for(var b={},d=Object.keys(c),f=0,e=d.length;f<e;f++){var g=d[f];b[g]=a[g]||c[g]}return b}},shortScale=[100],i=1;16>=i;i++)shortScale.push(Math.pow(10,3*i));for(var longScale=[100,1E3],i=1;15>=i;i++)longScale.push(Math.pow(10,6*i));writtenNumber.defaults={noAnd:!1,lang:"vn"};
function writtenNumber(a,c){c=c||{};c=util.defaults(c,writtenNumber.defaults);if(0>a)return"";a=Math.round(+a);var b="string"===typeof c.lang?i18n[c.lang]:c.lang,d=b.useLongScale?longScale:shortScale,f=b.units,e;if(!(f instanceof Array)){var g=f,f=[],d=Object.keys(g),h;for(h in d)f.push(g[d[h]]),d[h]=Math.pow(10,parseInt(d[h]))}b||(0>languages.indexOf(writtenNumber.defaults.lang)&&(writtenNumber.defaults.lang="en"),b=i18n[writtenNumber.defaults.lang]);var l=b.base;if(b.unitExceptions[a])return b.unitExceptions[a];
if(l[a])return l[a];if(100>a)return handleSmallerThan100(a,b,e,l,c);var m=a%100,g=[];m&&(!c.noAnd||b.andException&&b.andException[10]?g.push(b.unitSeparator+writtenNumber(m,c)):g.push(writtenNumber(m,c)));var n;h=0;for(var q=f.length;h<q;h++){var k=Math.floor(a/d[h]),k=k%(h===q-1?1E6:d[h+1]/d[h]);e=f[h];if(k)if(n=d[h],e.useBaseInstead)-1<e.useBaseException.indexOf(k)&&(e.useBaseExceptionWhenNoTrailingNumbers?0===h&&g.length:1)?g.push(1<k&&e.plural?e.plural:e.singular):g.push(l[k*d[h]]);else{var p;
p="string"===typeof e?e:!(1<k&&e.plural)||e.avoidInNumberPlural&&m?e.singular:e.plural;e.avoidPrefixException&&-1<e.avoidPrefixException.indexOf(k)?g.push(p):(e=b.unitExceptions[k]||writtenNumber(k,util.defaults({noAnd:!(b.andException&&b.andException[k]||e.andException)&&!0},c)),a-=k*d[h],g.push(e+" "+p))}}c=n*Math.floor(a/n);b.andWhenTrailing&&n&&0<a-c&&0!==g[0].indexOf(b.unitSeparator)&&(g=[g[0],b.unitSeparator.replace(/\s+$/,"")].concat(g.slice(1)));a=g.reverse().join(" ");return a.substring(0,
1).toUpperCase()+a.substring(1)}function handleSmallerThan100(a,c,b,d,f){var e=10*Math.floor(a/10);return(b=a-e)?d[e]+c.baseSeparator+writtenNumber(b,f):d[e]}appInfoService.factory("numberToWord",[function(){return writtenNumber}]);
