accApp.directive("ngTypeahead",["$http",function(m){return{restrict:"E",scope:{ngModel:"=",ngDisabled:"=?",ngShow:"=?",label:"=?",onSelect:"&?",fieldModel:"@",module:"@",condition:"@",defaultValues:"@",parentData:"=?",setFields:"@"},template:function(a,d){a="<div class='inner-addon right-addon'><input type='text' ng-blur='blur()' ng-change='label=undefined' typeahead-on-select = 'getItem($item, $model, $label)'";d.hasOwnProperty("ngRequired")&&(a=a+" ng-required='"+d.ngRequired+"'");d.hasOwnProperty("ngDisabled")&&
(a+=" ng-disabled='ngDisabled'");d.hasOwnProperty("ngShow")&&(a+=" ng-show='ngShow'");a=d.hasOwnProperty("group")?a+"typeahead-min-length='2' typeahead-template-url='templates/"+d.group+"/"+d.module+"/templates/typeahead.html' ":a+"typeahead-min-length='2' typeahead-template-url='templates/lists/"+d.module+"/templates/typeahead.html' ";d.hasOwnProperty("placeholder")&&(a=a+" placeholder='"+d.placeholder+"' ");a=a+" ng-model='ngModel' uib-typeahead='item."+d.fieldModel+" as item."+d.fieldModel+" for item in getList($viewValue,10)' class='form-control'>";
if(void 0==d.showButtonList||1==d.showButtonList)d.hasOwnProperty("ngDisabled")||(a+="<i class='glyphicon glyphicon-triangle-bottom'  ng-show='show_btn_list'   ng-click='showList()'></i>");return a+"</div>"},controller:["$scope","$uibModal","$window","$interval","$rootScope","$q","$timeout",function(a,d,f,v,p,q,n){if(f=STPModules[a.module.toLowerCase()]){var k=f.obj;a.pathService=k.server_path;a.fieldsSearch=k.fields_find;a.setData4Fields=function(c){if(a.parentData&&a.setFields){var e=eval("({"+
a.setFields+"})"),b;for(b in e)a.parentData[b]=c?c[e[b]]:void 0}};var t=function(c,e,b,d){var g=q.defer(),r=p.getCacheFactory(c,"SYSTEM"),l=a.pathService,l=_.isObject(e)?l+JSON.stringify(e):l+e?e:"";if(_online){var h=_.contains(paths_not_require_id_app,a.pathService)?server_url+"/api/"+a.pathService+"?t=1":server_url+"/api/"+c+"/"+a.pathService+"?t=1";d&&(h=h+"&limit="+d);if(e)if(angular.isObject(e))var u=JSON.stringify(e),h=h+"&q="+u;else h=h+"&"+e;!b&&a.fields&&(b=a.fields);b&&(h=h+"&fields="+b);
m.get(h).then(function(a){r.put(l,a.data);g.resolve(a)},function(a){a.data?g.reject(a):(a=r.get(l))?g.resolve({data:a}):k.getService(m,q,p).filterOffline(c,{condition:e,fields:b,limit:d}).then(function(a){g.resolve(a)},function(a){g.reject(a)})})}else(h=r.get(l))?g.resolve({data:h}):k.getService(m,q,p).filterOffline(c,{condition:e,fields:b,limit:d}).then(function(a){g.resolve(a)},function(a){g.reject(a)});return g.promise};a.prepareCondition=function(c){var e={},b;if(a.condition)try{var d=eval("({"+
a.condition+"})");_.extend(e,d)}catch(g){console.error("error parse script",a.condition,g)}if(c)if(_online){if("$text"==a.fieldsSearch)return"$text="+c;e.$or=[];a.fieldsSearch.forEach(function(a){b=0==a.toLowerCase().indexOf("tk")?eval("({'"+a+"':{$regex:'^"+c+"',$options:'i'}})"):eval("({'"+a+"':{$regex:'"+c+"',$options:'i'}})");e.$or.push(b)})}else e.value_for_find=c;return e};a.getList=function(c,e,b){c=a.prepareCondition(c);return t(id_app,c,null,e).then(function(a){a=a.data;b&&b(a);return a})};
a.getItem=function(c,e,b){a.fieldLabel&&(a.label=c[a.fieldLabel]);a.setData4Fields(c);a.onSelect&&n(function(){a.onSelect({$item:c})},100)};a.blur=function(){if(a.ngModel&&!a.label&&a.fieldLabel){var c=eval("({"+a.fieldModel+":'"+a.ngModel+"'})");if(a.condition){var e=eval("({"+a.condition+"})");_.extend(c,e)}t(id_app,c,a.fieldLabel).then(function(b){var c=b.data;a.label||(1==c.length?(a.setData4Fields(c[0]),a.label=c[0][a.fieldLabel]):(a.setData4Fields(),a.ngModel=void 0));a.onSelect&&n(function(){a.onSelect({$item:0<
c.length?c[0]:{}})},100)})}a.ngModel||a.onSelect&&n(function(){a.onSelect({$item:{}})},100)};a.showList=function(){d.open({templateUrl:"templates/"+a.group+"/"+a.module+"/templates/dialog-select.html",controller:["$scope","$uibModalInstance","parentScope",a.module,"$rootScope",function(a,e,b,f,g){a.getList=function(c,e){b.getList(c,e,function(b){a.items=b})};a.keyup=function(b,c){13==b.keyCode&&c&&a.getList(c)};a.select=function(a){b.ngModel=a[b.fieldModel];b.fieldLabel&&(b.label=a[b.fieldLabel]);
b.setData4Fields(a);b.onSelect&&n(function(){b.onSelect({$item:a})},100);e.close()};a.cancel=function(){e.close()};a.openList=function(){var a=b.module;if(b.condition){var c=eval("({"+b.condition+"})"),d="",f;for(f in c)d=d?d+"&"+f+"="+c[f]:f+"="+c[f];d&&(a=a+"?"+d)}g.openUrl(a);e.close()};a.quickadd=function(){var a={};b.defaultValues&&(a=eval("({"+b.defaultValues+"})"));k.quickadd(d,function(a){b.ngModel=a[b.fieldModel];b.fieldLabel&&(b.label=a[b.fieldLabel]);b.setData4Fields(a)},a);e.close()};
a.quickedit=function(a){k.quickedit(d,a._id,function(c){_.extend(a,c);b.setData4Fields(a)})};a.delete=function(b){g.confirm("B\u1ea1n c\u00f3 ch\u1eafc ch\u1eafn x\u00f3a kh\u00f4ng?").then(function(c){1==c&&f.delete(id_app,b._id).then(function(c){a.items=_.filter(a.items,function(a){return a._id!==b._id})},function(a){(a=a.data)||(a="Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7");g.alert(a)})})};a.getList("",10)}],size:"xs",resolve:{parentScope:function(){return a}}})}}}],link:function(a,
d,f,m){a.show_btn_list=!0;f.hasOwnProperty("fields")&&(a.fields=f.fields);f.hasOwnProperty("fieldLabel")&&(a.fieldLabel=f.fieldLabel);f.hasOwnProperty("group")?a.group=f.group:a.group="lists";a.$watch("ngModel",function(d,f){a.ngModel||(a.label="")})}}}]);
