var $jscomp={scope:{},findInternal:function(a,b,d){a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var k=a[e];if(b.call(d,k,e,a))return{i:e,v:k}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,c={next:function(){if(d<a.length){var e=d++;return{value:b(e,a[e]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
var appModule_edit_add=function(a,b){a.addUser=function(){b.$uibModal.open({templateUrl:"templates/lists/app/templates/add-user.html",controller:["$scope","$controller","$http","$location","parentScope","$uibModalInstance","$window","$routeParams","$timeout","$rootScope",function(a,c,b,k,g,f,h,p,m,n){a.save=function(){b.get(server_url+"/check-user/"+a.email_coll).then(function(c){c=c.data;var e={email:a.email_coll,name:a.name_coll,password:a.password,rePassword:a.re_password};c?g.addParticipant({name_coll:a.name_coll,
email_coll:a.email_coll,picture_coll:c.picture,group_id:a.group_id,admin:a.admin},function(a){a||f.close()}):a.auto_create_user&&b.post(server_url+"/signup",e).then(function(c){n.alert(c.data);g.addParticipant({name_coll:e.name,email_coll:e.email,group_id:a.group_id,admin:a.admin},function(a){a||f.close()})},function(a){n.alert(a.data)})},function(a){n.alert(a.data)})};a.cancel=function(){f.close()}}],size:"md",backdrop:"static",resolve:{parentScope:function(){return a}}})}},appModule=new baseInput("app",
"app",["name"],"Th\u00f4ng tin \u0111\u01a1n v\u1ecb, doanh nghi\u1ec7p",{modal_size:"md",services:function(a){return{active:function(b){return a.get(server_url+"/api/app/active/"+b)},notaccept:function(b){return a.get(server_url+"/api/app/notaccept/"+b)}}},onAdd:appModule_edit_add,onEdit:appModule_edit_add,onView:function(a,b){appModule_edit_add(a,b);a.onUpdated=function(a){b.$rootScope.app_info&&(b.$rootScope.app_info=JSON.parse(JSON.stringify(a)))};if(a.current_user.email===a.data.user_created)a.current_user.appAdmin=
!0;else{var d=_.find(a.data.participants,function(c){return c.email==a.current_user.email});a.current_user.appAdmin=d&&d.admin?!0:!1}a.sync=function(){var c=server_url_report+"/api/"+id_app+"/sync";a.$emit("$dataChangeStart");a.syncing=!0;a.error="";b.$http.get(c).then(function(c){a.$emit("$dataChangeSuccess");a.syncing=!1;b.$rootScope.alert("Ch\u01b0\u01a1ng tr\u00ecnh \u0111\u00e3 th\u1ef1c hi\u1ec7n xong")},function(c){a.syncing=!1;(c=c.data)||(c="Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7");
b.$rootScope.alert(c);a.$emit("$dataChangeError")})};a.createLinkVoiIP=function(c){c=server_url+"/api/app/getTokenForVoiIP/"+c;a.data.voiIPTokens||(a.data.voiIPTokens=[]);b.$http.get(c).then(function(c){a.data.voiIPTokens.push(c.data.token)},function(a){b.$rootScope.alert(a.data)})};a.deleteLinkVoiIP=function(c,e){a.data.voiIPTokens||(a.data.voiIPTokens=[]);a.data.voiIPTokens=_.reject(a.data.voiIPTokens,function(a){return a===e});a.update(a.data,function(a){if(a)return b.$rootScope.alert(a)})};a.deleteTokenSTPAPI=
function(){a.data.stp_api_token="";a.data.stp_api_address="";a.update(a.data,function(c){if(c)return b.$rootScope.alert(c);id_app==a.data._id.toString()&&b.$rootScope.commands.forEach(function(a){"STP"==a.name&&(a.visible=!1)});b.$rootScope.alert("Ch\u01b0\u01a1ng tr\u00ecnh \u0111\u00e3 th\u1ef1c hi\u1ec7n xong")})};a.getTokenSTPAPI=function(){if(a.data.stp_api_address&&a.current_user.appAdmin){var c=a.data.stp_api_address;b.$uibModal.open({templateUrl:"templates/lists/app/templates/loginSTPAPI.html",
controller:["$scope","$uibModalInstance","user","$location","$rootScope","$http","parentScope",function(a,b,d,f,h,p,m){a.data={username:"admin"};a.getToken=function(){a.messageError="";p.get(server_url+"/api/"+id_app+"/ent-token?address="+c+"&username="+a.data.username+"&password="+a.data.password).then(function(c){(c=c.data)?0<=c.indexOf("ERROR")?a.messageError=c:(m.data.stp_api_token=c.split('"').join(""),id_app==m.data._id.toString()&&h.commands&&h.commands.forEach(function(a){"STP"==a.name&&(a.visible=
!0)}),b.close()):a.messageError="Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7"},function(b){a.messageError=b.data?b.data:"Kh\u00f4ng k\u1ebft n\u1ed1i \u0111\u01b0\u1ee3c v\u1edbi server API t\u1ea1i "+c})}}],size:"md",resolve:{parentScope:function(){return a}}})}};a.addParticipant=function(c,e){c.picture_coll||(c.picture_coll="/images/avatar.jpg");e||(e=function(){});a.participant=void 0;a.data.participants||(a.data.participants=[]);if(_.find(a.data.participants,function(a){return a.email==
c.email_coll}))return b.$rootScope.alert(c.email_coll+" \u0111\u00e3 t\u1ed3n t\u1ea1i"),e(c.email_coll+" \u0111\u00e3 t\u1ed3n t\u1ea1i");var d=[];a.data.participants.forEach(function(a){d.push(a)});d.push({email:c.email_coll,name:c.name_coll,picture:c.picture_coll,group_id:c.group_id,admin:c.admin});a.update({_id:a.data._id,participants:d},function(g){if(g)return b.$rootScope.alert("Kh\u00f4ng th\u1ec3 th\u00eam ng\u01b0\u1eddi d\u00f9ng "+c.email_coll+" cho \u0111\u01a1n v\u1ecb n\u00e0y"),console.log(g),
e("Kh\u00f4ng th\u1ec3 th\u00eam ng\u01b0\u1eddi d\u00f9ng "+c.email_coll+" cho \u0111\u01a1n v\u1ecb n\u00e0y");a.data.participants=d;e()})};a.deleteParticipant=function(c){a.data.participants||(a.data.participants=[]);var e=_.reject(a.data.participants,function(a){return a.email==c});a.update({_id:a.data._id,participants:e},function(d){d?(b.$rootScope.alert("Kh\u00f4ng th\u1ec3 x\u00f3a ng\u01b0\u1eddi d\u00f9ng "+c+" c\u1ee7a \u0111\u01a1n v\u1ecb n\u00e0y"),console.log(d)):a.data.participants=
e})};a.open=function(c){var d=c._id;c.active||b.service.active(d).then(function(a){},function(a){console.error("Kh\u00f4ng th\u1ec3 k\u00edch ho\u1ea1t: ",a.data)});id_app=d;b.$rootScope.app_info=_.find(a.list,function(a){return a._id==d});b.$rootScope.id_app=d;b.$localStorage.set("id_app",d);b.$rootScope.w_redirect?(w_redirect=b.$rootScope.w_redirect,delete b.$rootScope.w_redirect,b.$location.url(w_redirect)):b.$rootScope.openDefaultInterface()};a.auth_google=function(){var c=b.$window.open(server_url+
"/auth/google","Google authentication","height=400,width=400"),d=b.$interval(function(){try{if(c.location.href&&c.location.href.indexOf("/auth/google/callback")&&c.document.body.innerHTML&&0<=c.document.body.innerHTML.indexOf("access_token")){var e=JSON.parse(c.document.title);a.update({google_drive_email:e.email,google_drive_token:e.access_token,google_drive_refresh_token:e.refresh_token},function(c,d){if(c)return b.$rootScope.alert(c);a.data.google_drive_refresh_token=access_token});b.$interval.cancel(d);
c.close()}}catch(g){}},500)};a.delete_google_drive=function(){a.update({google_drive_email:"",google_drive_token:"",google_drive_refresh_token:""},function(c,b){if(c)return alert(c);a.data.google_drive_refresh_token=""})};a.backupApp=function(a){var c=(server_url_backup_restore||server_url)+"/api/app/backup/"+a+"?access_token="+b.$rootScope.token;b.$timeout(function(){b.$rootScope.downloadFile(c,"backup.zip",function(a){a&&console.log("error backup data",a)})},0);b.$rootScope.toast("Ch\u01b0\u01a1ng tr\u00ecnh \u0111ang sao l\u01b0u d\u1eef li\u1ec7u. H\u00e3y ch\u1edd \u0111\u1ee3i trong gi\u00e2y l\u00e1t")};
a.restoreAppUrl=function(){return(server_url_backup_restore||server_url)+"/api/app/restore/"+id_app+"?access_token="+b.$rootScope.token};a.$on("$fileUploadSuccess",function(a,d){b.$rootScope.toast(d)});a.$on("$fileUploadError",function(a,d){b.$rootScope.alert("L\u1ed7i: "+d||"Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i v\u1edbi m\u00e1y ch\u1ee7")})},has_view:!0});appModule.defaultValues={ngay_dn:new Date(2015,0,1),ngay_ks:new Date(2015,0,1),ngay_ky1:new Date(2015,0,1)};
appModule.module.controller("initApp",["$scope","$window","$interval","$http",function(a,b,d,c){}]);appModule.init=function(a,b){b("initApp",{$scope:a})};
appModule.module.controller("baseAppHomeController",["$scope","$location","$localStorage","$rootScope","app","$window",function(a,b,d,c,e,k){a.detail=function(b,f){f||e.active(b).then(function(a){},function(a){console.error("Kh\u00f4ng th\u1ec3 k\u00edch ho\u1ea1t: ",a.data)});id_app=b;c.app_info=_.find(a.list,function(a){return a._id==b});c.id_app=b;d.set("id_app",b);a.view(b)};a.open=function(g,f){f||e.active(g).then(function(a){},function(a){console.error("Kh\u00f4ng th\u1ec3 k\u00edch ho\u1ea1t: ",
a.data)});id_app=g;c.app_info=_.find(a.list,function(a){return a._id==g});c.id_app=g;d.set("id_app",g);c.w_redirect?(w_redirect=c.w_redirect,delete c.w_redirect,b.url(w_redirect)):c.openDefaultInterface()}}]);appModule.initHomeController=function(a,b){a("baseAppHomeController",{$scope:b})};
var initAddEditController=function(a,b){b.addParticipant=function(a,c){c||(c=function(){});b.participant=void 0;b.data.participants||(b.data.participants=[]);if(_.find(b.data.participants,function(c){return c.email==a.email_coll}))return alert(a.email_coll+" \u0111\u00e3 t\u1ed3n t\u1ea1i"),c(a.email_coll+" \u0111\u00e3 t\u1ed3n t\u1ea1i");b.data.participants.push({email:a.email_coll,name:a.name_coll,picture:a.picture_coll,admin:a.admin,group_id:a.group_id});c()};b.deleteParticipant=function(a){b.data.participants||
(b.data.participants=[]);b.data.participants=_.reject(b.data.participants,function(c){return c.email==a})}};appModule.initAddController=function(a,b){initAddEditController(a,b)};appModule.initEditController=function(a,b){initAddEditController(a,b)};
appModule.module.controller("appsController",["$scope","$rootScope","$routeParams","$http","user","$location","$uibModal","app","appInfo",function(a,b,d,c,e,k,g,f,h){h.info("app",function(b,e,f){b||(b=d.email,c.get(server_url+"/api/app/apps/"+b).then(function(c){a.list=c.data}),a.email=b,a.openProfile=function(a){viewProfile(g,a)},a.addDays=function(a){g.open({templateUrl:"templates/lists/app/templates/add-days.html",controller:["$scope","$uibModalInstance","user","$location","$rootScope","app","$window",
function(c,b,d,e,g,f,h){c.so_ngay=30;c.cancel=function(){b.close()};c.save=function(d){d={};_.extend(d,a);var e=d.expire_date,e=!e||0>=d.so_ngay_con_lai?new Date:new Date(e);e.setDate(e.getDate()+c.so_ngay);d.expire_date=e;f.update(d._id,d._id,d).then(function(c){_.extend(a,c.data);b.close()},function(a){g.alert("Kh\u00f4ng th\u1ec3 th\u00eam ng\u00e0y s\u1eed d\u1ee5ng cho c\u00f4ng ty n\u00e0y\n"+a.data)})}}],size:"lg"})})})}]);
appModule.module.controller("queryController",["$scope","$rootScope","$routeParams","$http","user","$location","$uibModal","app","appInfo",function(a,b,d,c,e,k,g,f,h){b.function_title="Query commander";b.function_code="Query";h.info("app",function(b,d,e){if(!b){var g=server_url_report+"/api/"+id_app+"/query/";a.action="find";a.model="socai";a.run=function(){if(a.action&&a.model){a.result=null;a.error=null;a.cols=null;var b=g+a.model+"/"+a.action+"?1=1";a.q&&(b=b+"&q="+a.q);a.limit&&(b=b+"&limit="+
a.limit);a.fields&&(b=b+"&fields="+a.fields);c.get(b).then(function(b){a.result=b.data;_.isArray(a.result)&&0<a.result.length&&(a.cols=_.keys(a.result[0]))},function(b){a.error=b.data})}}}})}]);
appModule.module.controller("assignController",["$scope","$rootScope","$routeParams","$http","user","$location","app","appInfo","trangthai",function(a,b,d,c,e,k,g,f,h){initLabel(b,a,f,"APP",c);f.info("app",function(e,g,f){e||h.load().then(function(g){var f=g.data;a.getTrangthai=function(a){var b=_.filter(f,function(b){return a&&b.ma_ct==a.toUpperCase()});b||(b=[]);return b};var h=d.id_app,l=d.email;a.email=l;a.name=k.search().name;c.get(server_url+"/api/"+h+"/menu").then(function(d){if(d.data){var g=
d.data.menu,f=server_url+"/api/"+h+"/right?q="+JSON.stringify({email:l}),k=[];c.get(f).then(function(d){var f=d.data;g.forEach(function(b){"1"==b.type&&b.input.forEach(function(b){if(b.items)b.items.forEach(function(b){b.module=b.module?b.module:b.path;var c=_.find(f,function(a){return a.module==b.module});if(c)for(var d in c)b[d]=c[d];else b.view=!1,b.add=!1,b.update=!1,b.delete=!1,b.print=!1,b.visible=!1;_.isArray(b.trang_thai)&&delete b.trang_thai;if(!b.trang_thai||_.isEqual({},b.trang_thai)){b.trang_thai=
{};var c=a.getTrangthai(b.module),e;for(e in c)b.trang_thai[e.ma_trang_thai]=!1}b.id_app=h;b.email=l;k.push(b)});else{b.module=b.module?b.module:b.path;var c=_.find(f,function(a){return a.module==b.module});if(c)for(var d in c)b[d]=c[d];else b.view=!1,b.add=!1,b.update=!1,b.delete=!1,b.print=!1,b.visible=!1,b.trang_thai={};if(!b.trang_thai){b.trang_thai={};var c=a.getTrangthai(b.module),e;for(e in c)b.trang_thai[e.ma_trang_thai]=!1}b.id_app=h;b.email=l;k.push(b)}});"2"==b.type&&b.input.forEach(function(b){b.items.forEach(function(b){b.module=
b.module?b.module:b.path;var c=_.find(f,function(a){return a.module==b.module});if(c)for(var d in c)b[d]=c[d];else b.view=!1,b.add=!1,b.update=!1,b.delete=!1,b.print=!1,b.visible=!1,b.trang_thai={};if(!b.trang_thai){b.trang_thai={};var c=a.getTrangthai(b.module),e;for(e in c)b.trang_thai[e.ma_trang_thai]=!1}b.id_app=h;b.email=l;k.push(b)})});"3"==b.type&&b.input.forEach(function(b){b.items.forEach(function(b){b.items.forEach(function(b){b.module=b.module?b.module:b.path;var c=_.find(f,function(a){return a.module==
b.module});if(c)for(var d in c)b[d]=c[d];else b.view=!1,b.add=!1,b.update=!1,b.delete=!1,b.print=!1,b.visible=!1,b.trang_thai={};if(!b.trang_thai){b.trang_thai={};var c=a.getTrangthai(b.module),e;for(e in c)b.trang_thai[e.ma_trang_thai]=!1}b.id_app=h;b.email=l;k.push(b)})})})});a.commands=g;a.save=function(){a.$emit("$dataSaveStart");async.map(k,function(b,c){a.change(b,2,c)},function(c,d){if(c)return a.$emit("$dataSaveError"),b.alert(c);a.$emit("$dataSaveSuccess");b.alert("Ch\u01b0\u01a1ng tr\u00ecnh \u0111\u00e3 th\u1ef1c hi\u1ec7n xong")})};
a.change=function(a,d,g){d||(d=1);g||(g=function(){});var f=server_url+"/api/"+h+"/right";a._id?(f=f+"/"+a._id,f=c.put(f,a)):f=c.post(f,a);f.then(function(b){b=b.data;for(var c in b)a[c]=b[c];g(null,a)},function(c){2!==d&&b.alert(JSON.stringify(c.data));g(e+"\n"+a.module+"/"+a.email)})};a.selectAllRight=function(b){b.add=b.sel;b.update=b.sel;b.delete=b.sel;b.view=b.sel;b.viewOfOther=b.sel;for(var c in b.trang_thai)b.trang_thai[c]=b.sel;a.change(b)};a.selectItems=function(b,c){a.items=b;a.group_title=
c}},function(a){console.log(f)})}},function(a){console.log("error when get command",a.data)})})})}]);appModule.module.config(["$routeProvider","$locationProvider",function(a,b){a.when("/assign/:id_app/:email",{templateUrl:"templates/lists/app/templates/assign.html",controller:"assignController"}).when("/query",{templateUrl:"templates/lists/app/templates/query.html",controller:"queryController"}).when("/apps/:email",{templateUrl:"templates/lists/app/templates/apps.html",controller:"appsController"})}]);
